# All plots for differential expression analysis results
#
# Author: vidal
###############################################################################

utils::globalVariables(c("Average Expression", "logFC", "log2 Fold-Change", "adj. P-Value", "label_id", "P-Value"))

#' Function to generate a M-A plot using `ggplot2`
#' @param dat data frame; annotated output table generated by performing pair-wise comparisons and
#'   corresponding statistical tests.
#' @param contr Character; contrast to be processed. This is either a column name of a contrast matrix or a character
#'   conforming to the same format.
#' @param id \code{character}. Name of the column with the IDs used for labeling. Used as fallback for \code{sym.col}.
#' @param sym.col \code{character}. Name of the column with the IDs used for labeling. Takes priority over \code{id}.
#' @param p.thr Numeric; P-Value threshold for filtering gene labels. Only genes (points) with a value below this threshold will be labeled.
#' @param fdr.thr Numeric; FDR threshold for filtering gene labels (see \code{p.thr}).
#' @param logfc.thr Numeric; FC threshold on the log2-scale for filtering gene labels.
#' @param numlab \code{numeric}. Maximum number of labels per plot. Overrides numbers calculated based on `p.thr` and `fdr.thr`.
#' @param out.dir Character; output directory for final tables.
#' @param analysis.name Character used in the output file name.
#' @param point.lab \code{logical}. Should points be labelled, at all?
#' @param biom.attributes \code{character}. Vector of column names to be retrieved from biomart.
#' @param font.size Size of point labels in M-A plots.
#' @param lists Logical; should output tables be written to files?
#' @export
diff_expr_ma_plot <-
		function(dat, contr, id=NULL, sym.col="gene_symbol", p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15,
		         out.dir=".", analysis.name=NULL, point.lab=TRUE, biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"),
		         font.size=5, lists=TRUE)
{
	if (is.null(id) && !sym.col %in% names(dat)) {
		stop("Need one of 'id' or 'sym.col'.")
	}
	if (sym.col %in% names(dat)) {
		dat$label_id <- dat[[sym.col]]
	} else if (id %in% names(dat)) {
		dat$label_id <- dat[[id]]
	} else {
		stop("No ID columns found.")
	}
	rn <- rownames(dat)
	pv.col <- names(dat)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(dat)))]
	fdr.col <- names(dat)[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(dat)))]
	numlab <- ceiling(1.25*numlab)
	A <- grep("^logCPM$|^AveExpr$", names(dat), value=TRUE)
	degFDR <- rn[dat[[fdr.col]] < fdr.thr & abs(dat$logFC) >= logfc.thr]
	degPval <- rn[dat[[pv.col]] < p.thr & abs(dat$logFC) >= logfc.thr]
	dat$`P-Value` <- dat[[pv.col]]
	dat$`adj. P-Value` <- dat[[fdr.col]]
	dat$`log2 Fold-Change` <- abs(dat$logFC)
	dat$`Average Expression` <- dat[[A]]
	# list to collect ggplot2 objects for output
	g.l <- list()
	cat("  M-A plot...\n")
	if (length(degFDR)>0) {
		cat(" FDR filtered values...\n")

		## ggplot2 M-A plot
		g <- ggplot(data=dat, aes(x=`Average Expression`, y=logFC))
		g <- g + geom_point(aes(size=`log2 Fold-Change`, color=`adj. P-Value`))
		g <- g + scale_colour_gradient2(low="#00106B", high="#A4B1FF", mid="#F3F5FF", midpoint=0.2)
		if (point.lab) {
			gene.lab <- dat[rn %in% degFDR, ]
			cat("    ", nrow(gene.lab), "point(s) labelled...\n")
			if (nrow(gene.lab)>numlab) {
				cat("     Restricting to", numlab, "...\n")
				ix <- sort(gene.lab$`adj. P-Value`, index=T)$ix
				gene.lab <- gene.lab[ix[1:numlab], ][order(ix[1:numlab]), ]
			}
			cat("   Highlighted features:\n")
			if (length(degFDR)>8) {
				print(gene.lab[1:8, 1:2])
				cat("_truncated_ (", length(degFDR), "features)\n")
			} else {
				print(gene.lab[1:8, 1:2])
			}
			g <- g + ggtitle(paste0("M-A plot for ", contr, " (highl.: FDR < ", fdr.thr, "; FC >= ", 2^logfc.thr, "-fold)"))
			g <- g + ggrepel::geom_text_repel(data = gene.lab, aes(label = label_id), size = font.size, box.padding = unit(0.35, "lines"), point.padding = unit(0.3, "lines"), max.overlaps = 15, show.legend = F)
			if (lists) {
				write.table(gene.lab, file.path(out.dir, paste(analysis.name, contr, "labelledPointsSmearPlot.tsv", sep="_")), sep="\t", quote=FALSE, row.names=FALSE)
			}
		} else {
			g <- g + ggtitle(paste("M-A plot for", contr))
		}
		suppressWarnings(print(g))
		g.l[["FDR"]] <- g
	}
	if (length(degPval)>0) {
		cat("    for P-value filtered values...\n")

		## ggplot implemetation of MA plot
		g <- ggplot(data=dat, aes(x=`Average Expression`, y=logFC))
		g <- g + geom_point(aes(size=`log2 Fold-Change`, color=`P-Value`))
		g <- g + scale_colour_gradient2(low="#00106B", high="#A4B1FF", mid="#F3F5FF", midpoint=0.2)
		if (point.lab) {
			gene.lab <- dat[rn %in% degPval, ]
			cat("    ", nrow(gene.lab), "point(s) labelled...\n")
			if (nrow(gene.lab)>numlab) {
				cat("     Restricting to", numlab, "...\n")
				ix <- sort(gene.lab$`P-Value`, index=T)$ix
				gene.lab <- gene.lab[ix[1:numlab], ][order(ix[1:numlab]), ]
			}
			cat("   Highlighted features:\n")
			if (length(degPval)>8) {
				print(gene.lab[1:8, 1:2])
				cat(paste0("   _truncated_ (", length(degPval), " features)\n"))
			} else {
				print(gene.lab[1:8, 1:2])
			}
			g <- g + ggtitle(paste0("M-A plot for ", contr, " (highl.: P-value < ", p.thr, "; FC >= ", 2^logfc.thr, "-fold)"))
			g <- g + ggrepel::geom_text_repel(data = gene.lab, aes(label = label_id), size = font.size, box.padding = unit(0.35, "lines"), point.padding = unit(0.3, "lines"), max.overlaps = 15, show.legend = F)
			if (lists) {
				write.table(gene.lab, file.path(out.dir, paste(analysis.name, contr, "labelledPointsSmearPlot.tsv", sep="_")), sep="\t", quote=FALSE, row.names=FALSE)
			}
		} else {
			g <- g + ggtitle(paste("M-A plot for", contr))
		}
		print(g)
		g.l[["Pval"]] <- g
	}
	return(g.l)
}


##' Helper function that returns volcano plot.
#' @param data.df \code{data.frame}. Data frame containing all necessary columns to generate a Volcano plot with
#'   gene labels (at least p-values, FDR values, log-ratios and gene symbols or other IDs)
#' @param property.to.plot \code{character}. Statistics to be plotted. One of "fdr", "p".
#' @param property.column \code{character}. Name of the actual column with to the statistics to be plotted.
#' @param property.thr \code{numeric}. Plotted values with a statistics (property) value below this threshold
#'   will be labelled in the respective plot.
#' @param logfc.thr \code{numeric}. Plotted (`abs`olute) values above this threshold will have bigger dots.
#' @param main \code{character}. Main plot title. (Will be complemented with additional information, e.g., 'FDR'
#'   when labelling according to and FDR threshold.)
#' @param numlab \code{numeric}. Maximum number of labels per plot. Supersedes numbers calculated based on `p.thr` and `fdr.thr`.
#' @param point.lab \code{logical}. Should points be labelled, at all?
#' @param sym.col \code{character}. Name of column with gene symbols, e.g., HGNC Symbols.
#' @param pretty.breaks \code{logical}. Should the breaks on the axes be pretty? Uses `scales::breaks_extended`.
#' @export
prepare_volcano_of_given_property = function(data.df, property.to.plot = c("fdr", "p"), property.column,
		property.thr, logfc.thr, main, numlab, point.lab, sym.col, pretty.breaks=FALSE){

  # test if needed packages are installed
  if (pretty.breaks && !requireNamespace("scales", quietly = TRUE)) {
    stop(
      paste("Package", sQuote("scales"), "must be installed to use the 'pretty.breaks' option."),
      call. = FALSE
    )
  }

	data.df[[property.to.plot]] <- data.df[[property.column]]

	# Formatted names to use in plot texts:
	property.formatted.name = toupper(property.to.plot)
	name.of.legend = paste0(property.formatted.name, "-values")
	legend.treshold.tag = paste0("signif. (", property.formatted.name, "<", property.thr, ")")
	#legend.treshold.tag = paste0("signif. (", property.formatted.name, "<", property.thr, " & ", "logFC>", logfc.thr, ")")
	subtitle.name = paste("(",")", sep=name.of.legend )
	x.axis.name = "Logarithmic fold change"
	y.axis.name = paste0("-log10(", property.formatted.name, ")")
	line.label.tag = "p" #except if we have FDR-values:
	if(property.to.plot == "fdr" ){
		line.label.tag = "q"
	}
	line_label_text = paste(line.label.tag, property.thr, sep = "=")

	# Constructing new bivalue column for coloring the points and displaying legend
	data.df[[name.of.legend]] <- "not signif."
	data.df[[name.of.legend]][data.df[[property.to.plot]] < property.thr] <- legend.treshold.tag
	#data.df[[name.of.legend]][data.df[[property.to.plot]] < property.thr & abs(data.df$logFC) > logfc.thr] <- legend.treshold.tag

	# Adding another bivalue column for magnitude of foldchange
	data.df$FC <- paste0("less than ", 2^logfc.thr, "-fold")
	data.df$FC[(data.df$logFC < -1*logfc.thr | data.df$logFC > logfc.thr)] <- paste0("more than ", 2^logfc.thr, "-fold")

	# Filtering data.df to label points
	filtdat <- data.df[data.df[[property.to.plot]] < property.thr & abs(data.df$logFC) > logfc.thr, ]
	cat("    ", nrow(filtdat), "point(s) labelled...\n")
	if (nrow(filtdat) > numlab) {
		cat("     Restricting to", numlab, "...\n")
		ix <- sort(filtdat[,property.to.plot], index=T)$ix
		filtdat <- filtdat[ix[1:numlab], ][order(ix[1:numlab]), ]
	}
	if (nrow(filtdat) & length(which(filtdat$logFC < 0)) < (numlab %/% 2.5) || nrow(filtdat) & length(which(filtdat$logFC > 0)) < (numlab %/% 2.5)) {
	  if (nrow(filtdat) & length(which(filtdat$logFC < 0)) < (numlab %/% 2.5)) {
	    filtdat1 <- rbind(filtdat, data.df[data.df[[property.to.plot]] < property.thr & data.df$logFC < logfc.thr, ])
	    filtdat1 <- filtdat1[!duplicated(filtdat1$ensembl_gene_id), ]
	  }
	  if (nrow(filtdat) & length(which(filtdat$logFC > 0)) < (numlab %/% 2.5)) {
	    filtdat1 <- rbind(filtdat, data.df[data.df[[property.to.plot]] < property.thr & data.df$logFC > logfc.thr, ])
	    filtdat1 <- filtdat1[!duplicated(filtdat1$ensembl_gene_id), ]
	  }
	  filtdat1 <- filtdat1[order(abs(filtdat1$logFC), decreasing = T), ]
	  filtdat <- filtdat1[1:min(nrow(filtdat1), numlab), ]

	  if (nrow(filtdat) & length(which(filtdat$logFC < 0)) < (numlab %/% 2.5) || nrow(filtdat) & length(which(filtdat$logFC > 0)) < (numlab %/% 2.5)) {
	    if (nrow(filtdat) & length(which(filtdat$logFC < 0)) < (numlab %/% 2.5)) {
	      filtdat.d <- data.df[data.df[[property.to.plot]] < property.thr & data.df$logFC < logfc.thr, ]
	      filtdat.d <- filtdat.d[!duplicated(filtdat.d$ensembl_gene_id), ]
	    } else {
	      filtdat.d <- data.df[which(data.df$logFC < 0), ]
	    }
	    filtdat.d <- filtdat.d[order(abs(filtdat.d$logFC), decreasing = T), ][1:min(nrow(filtdat.d), numlab), ]
	    if (nrow(filtdat) & length(which(filtdat$logFC > 0)) < (numlab %/% 2.5)) {
	      filtdat.u <- data.df[data.df[[property.to.plot]] < property.thr & data.df$logFC > logfc.thr, ]
	      filtdat.u <- filtdat.u[!duplicated(filtdat.u$ensembl_gene_id), ]
	    } else {
	      filtdat.u <- data.df[which(data.df$logFC > 0), ]
	    }
	    filtdat.u <- filtdat.u[order(abs(filtdat.u$logFC), decreasing = T), ][1:min(nrow(filtdat.u), numlab), ]

	    filtdat1 <- rbind(filtdat.d, filtdat.u)
	    filtdat1 <- filtdat1[abs(filtdat1$logFC) > logfc.thr, ]
	    filtdat1 <- filtdat1[order(abs(filtdat1$logFC), decreasing = T), ]
	    filtdat <- filtdat1[1:min(nrow(filtdat1), numlab), ]
	  }
	}

	# Constructing the plot
	volcano.plot <- ggplot(data.df, aes(x = logFC, y = -log10(data.df[, property.to.plot])))# ,
	volcano.plot <- volcano.plot + geom_point(inherit.aes= TRUE, aes(color = .data[[name.of.legend]]), size = 1.75)
	volcano.plot <- volcano.plot + scale_alpha_discrete(range = c(0.04, 0.5))
	volcano.plot <- volcano.plot + theme_bw(base_size = 10)

	volcano.plot <- volcano.plot + theme(panel.border = element_blank(),
			axis.line = element_line(color='black'),
			panel.grid.major = element_line(linewidth = 0.2),
			panel.grid.minor = element_line(linewidth = 0.2))

	volcano.plot <- volcano.plot + xlab(x.axis.name) + ylab(y.axis.name)
	volcano.plot <- volcano.plot + labs(color = name.of.legend)

	#volcano.plot <- volcano.plot + scale_color_manual(values=c("#0066FF", "#CC0000"))
	if (pretty.breaks) {
	  volcano.plot <- volcano.plot + scale_x_continuous(breaks = scales::breaks_extended(n=6)) + scale_y_continuous(breaks = scales::breaks_extended(n=8))
	}

	volcano.plot <- volcano.plot + geom_hline(aes(yintercept=-log10(property.thr)), colour="red", linetype="dashed")
	volcano.plot <- volcano.plot + geom_vline(aes(xintercept=logfc.thr), colour="red", linetype="dashed")
	volcano.plot <- volcano.plot + geom_vline(aes(xintercept=-logfc.thr), colour="red", linetype="dashed")

	volcano.plot <- volcano.plot + ggtitle(main, subtitle = subtitle.name) +
			theme(plot.title = element_text(hjust = 0.5)) +
			theme(plot.subtitle = element_text(hjust = 0.5)) #hjust 0.5 for centering

	volcano.plot <- volcano.plot + geom_text(inherit.aes= FALSE, data=data.df, aes(x=floor(min(logFC)), y=-log10(property.thr)), label = line_label_text, nudge_x=0.5, nudge_y=max(-log10(data.df[,property.to.plot]))/nrow(data.df), size=3.5, color="red")
	#volcano.plot <- volcano.plot + geom_text(x=0, y=0, label="two-fold FC", size=3, color="red") # TO DO: FIND GOOD POSITION, USE VARIABLE (fold change can sometimes be other than 2-fold?)

	if (point.lab && nrow(filtdat)>0) {

		volcano.plot <- volcano.plot + ggrepel::geom_text_repel(inherit.aes= FALSE,
				data = filtdat,
				aes(x= filtdat$logFC, y = -log10(.data[[property.to.plot]]), label = .data[[sym.col]]),
				size = 3,
				colour = "gray30",
				box.padding = unit(0.35, "lines"),
				point.padding = unit(0.3, "lines"),
				show.legend = F
		)

	}

	return(volcano.plot)
}

#' Function to generate a Volcano plot using `ggplot2`
#' @description `diff_expr_volcano_plot` generates two Volcano plots highlighing genes that are differentially expressed beyond custom thresholds for siginificance (set by parameters `p.thr` and fdr.thr`) and differential expression level (set by parameter `logfc.thr`).
#' @param d3 \code{data.frame}. Data frame containing all necessary columns to generate a Volcano plot with gene labels (at least p-values, FDR values, log-ratios and gene symbols or other IDs)
#' @param id \code{character}. Name of the gene ID column. Can be the same as `sym.col` but usually refers to an additional column with, e.g., Ensembl Gene IDs.
#' @param sym.col \code{character}. Name of column with gene symbols, e.g., HGNC Symbols.
#' @param main \code{character}. Main plot title. (Will be complemented with additional information, e.g., 'FDR' when labelling according to and FDR threshold.)
#' @param p.thr \code{numeric}. Plotted values with a P-Value below this threshold will be labelled in the P-Value plot.
#' @param fdr.thr \code{numeric}. Plotted values with a FDR below this threshold will be labelled in the FDR plot.
#' @param logfc.thr \code{numeric}. Plotted (`abs`olute) values above this threshold will have bigger dots.
#' @param numlab \code{numeric}. Maximum number of labels per plot. Takes precedence to numbers calculated based on `p.thr` and `fdr.thr`.
#' @param point.lab \code{logical}. Should points be labelled, at all?
#' @export
diff_expr_volcano_plot <-
		function(d3, id, sym.col="gene_symbol", main=NULL, p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, point.lab=TRUE)
{
	pv.col <- names(d3)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
	fdr.col <- names(d3)[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]

	if (point.lab) {
		cont.dat <- d3[, c(id, sym.col, "logFC", pv.col, fdr.col)]
		if (any(cont.dat$gene_symbol=="") || any(is.na(cont.dat$gene_symbol))) {
			repl <- which(cont.dat$gene_symbol==""|is.na(cont.dat$gene_symbol))
			cont.dat[repl, sym.col] <- cont.dat[repl, as.character(id)]
		}
	} else {
		cont.dat <- d3[, c(id, "logFC", pv.col, fdr.col)]
	}


	g.l <- list()
	g.l[["FDR"]] = prepare_volcano_of_given_property(data.df = cont.dat,
			property.to.plot = 'fdr',
			property.column = fdr.col,
			property.thr = fdr.thr,
			logfc.thr = logfc.thr,
			main = main,
			numlab = numlab,
			point.lab = TRUE,
			sym.col = sym.col)

	g.l[["Pval"]] = prepare_volcano_of_given_property(data.df = cont.dat,
			property.to.plot = 'p',
			property.column = pv.col,
			property.thr = p.thr,
			logfc.thr = logfc.thr,
			main = main,
			numlab = numlab,
			point.lab = TRUE,
			sym.col = sym.col)

	#Printing the plots so they can be stored into pdf-file when this function is called
	suppressWarnings(print(g.l[["Pval"]]))
	suppressWarnings(print(g.l[["FDR"]]))

	return(g.l)

}

#' Function to generate a histogram of the P-Value distribution
#' @param d3 \code{data.frame}. Data frame containing a P-Value column to generate a histogram. The column name will be determined
#'   by pattern matching.
#' @export
diff_expr_pval_hist_plot <-
		function(d3)
{
	cat("   Histogram of P-value distribution...\n")
	pv.col <- names(d3)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
	hist(d3[[pv.col]],breaks=20, xlab="P Value", ylab="Frequency", main="P-value distribution")
}


