# Functions for performing differential expression analysis
#
# Author: vidal
###############################################################################

#' Function to compute linear model fit and optionally apply 'voom' beforehand
#' @param counts Count matrix.
#' @param d Passed to \code{voom.fun}: a numeric matrix containing raw counts, or an ExpressionSet containing raw counts,
#'   or a DGEList object.
#' @param design Numeric design matrix.
#' @param do.voom Logical; should data be "voomed"?
#' @param voom.fun Voom function: one of "voom", "voomWithQualityWeights".
#' @param norm.method Character; one of "quantile", "tmm".
#' @param quasi.likelihood Logical; should quasi-likelihood methods be used? See \emph{Details} section.
#'   If \code{TRUE}, the default, then the quasi-likelihood methods are used, if \code{FALSE}, then the
#'   likelihood ratio test is used. Olease note the main wrapper function \code{diffExpr()} will set this parameter.
#' @param bayes.trend Logical passed to \code{eBayes()}: should an intensity-dependent trend be allowed for the prior variance?
#'   If FALSE then the prior variance is constant.
#'   Alternatively, trend can be a row-wise numeric vector, which will be used as the covariate for the prior variance.
#' @param bayes.robust Logical passed to \code{eBayes()}: should the estimation of df.prior and var.prior be robustified
#'   against outlier sample variances?
#' @param pairs Factor of identifiers specifying paired samples for paired or other block designs, or batch effects.
#' @param pairs_col \code{character}. Name of the column in 'samp.info' containing paired sample information.
#' @param block \code{logical}. Are the comparisons to be made within AND between subjects? See Details section.
#' @param contrasts Contrast matrix as generated by \code{makeContrasts()}. If \code{NULL}, the default, the design matrix
#'   is expected to describe simple pair-wise comparisons, i.e., with the contrasts already included in the matrix.
#'   Consequently, in that case, no contrasts will be fitted.
#' @param disp Character; one of "tagwise.dispersion", "trended.dispersion", "bin.dispersion"
#' @details For experimental designs involving comparisons within as well as between subjects inter-subject needs to be computed.
#'     In this case, the column specified in the 'pairs' argument must assign the subjects to the treatment/tissue/etc groups.
#'     For example, if we have two treatments the effects of which are to be observed in each two tissues, this design would apply.
#'     The 'pairs' factor is passed to the functions \code{duplicateCorrelation()} and \code{lmFit()}.
#'     Quasi-likelihood pipeline:
#'     While the likelihood ratio test is a more obvious choice for inferences with GLMs, the QL
#'     F-test is preferred as it reflects the uncertainty in estimating the dispersion for each gene. It
#'     provides more robust and reliable error rate control when the number of replicates is small.
#'     The QL dispersion estimation and hypothesis testing is done by using the functions
#'     glmQLFit() and glmQLFTest().
#' @export
diff_expr_fit <-
  function(counts, d, design, do.voom=TRUE, voom.fun=limma::voom, norm.method=c("quantile", "tmm"), quasi.likelihood=TRUE,
           bayes.trend=FALSE, bayes.robust=FALSE, pairs=NULL, pairs_col=NULL, block=FALSE, contrasts=NULL, disp="tagwise.dispersion")
  {
    if (do.voom) {
      if (norm.method=="tmm") {
        cts <- d
        norm.method="none"
        # TMM normalisation factors are calculated and added to the DGEList object. If voom is used then counts should usually not be renormalised,
        # so norm.method is set to "none", but "any normalization factors found in 'cts' will still be used even if normalize.method="none".
        # Gordon Smyth notes:
        # I wouldn't recommend TMM before quantile normalization, but it won't make much difference. If you apply scale normalization (such as TMM)
        # then follow it up with quantile normalization of the logCPM values, then the scale normalization will be overwritten. Scale normalization
        # becomes essentially an additive constant on the log-scale for each library, so it will be removed by quantile normalization.
        # We have never recommended using multiple normalization methods together as it confuses the issue somewhat.
      } else {
        cts <- counts
      }
      v <- voom.fun(cts, design=design, plot=FALSE, normalize.method=norm.method)

      # For paired samples or block designs:
      if (block && !is.null(pairs)) {
        if (!is.factor(pairs)) {
          stop("For block designs 'pairs' needs to be a factor.")
        }
        cat("  Samples are paired. Using column", sQuote(pairs_col), "as block variable...\n")
        cat("    ", levels(pairs), "\n")
        cat("  Calculating consensus correlation...\n")
        corfit <- limma::duplicateCorrelation(v$E , design, block=pairs)
        cat("  Fitting linear model using consensus correlation...\n")
        fit <- limma::lmFit(v, design, block=pairs, correlation=corfit$consensus)
      } else {
        cat("  Fitting linear model...\n")
        fit <- limma::lmFit(v, design)
      }
      if (!is.null(contrasts)) {
        # Contrasts have been provided in a character vector and a contrast matrix was created, so pair-wise comparisons
        # are calculated here. Since we used voom limma function are applied.
        if (length(grep("^Intercept$", rownames(contrasts)))) {
          rownames(contrasts)[grep("^Intercept$", rownames(contrasts))] <- "(Intercept)"
        }
        cat("  Fitting contrasts...\n")
        fit2 <- limma::contrasts.fit(fit, contrasts)
        cat("  eBayes fit...\n")
        fit2 <- limma::eBayes(fit2, trend = bayes.trend, robust = bayes.robust)
      } else {
        # Contrasts are "included" in the design, i.e., pair-wise comparisons have already been calculated in the lmFit() call.
        # Here, only the Bayes fit will be added.
        cat("  eBayes fit...\n")
        fit2 <- limma::eBayes(fit, trend = bayes.trend, robust = bayes.robust)
      }
      return(list(v=v, fit=fit, fit2=fit2))
    } else {
      ## Estimate dispersion values, relative to the design matrix, using the Cox-Reid (CR)-adjusted likelihood
      # Note, that batch effects or paired or blocked designs are taken into account in the design matrix and will be considered in the respective model.
      cat("  Estimating dispersion values...\n")
      d2 <- edgeR::estimateDisp(d, design)
      # Given the design matrix and dispersion estimates, fit a GLM to each feature.
      # If quasi-likelihood methods are used, estimate the gene-wise quasi-dispersions with empirical Bayes moderation.
      cat("  Fitting linear model...\n")
      if (quasi.likelihood) {
        fit <- edgeR::glmQLFit(d2, design, dispersion=d2[[disp]], robust=bayes.robust, abundance.trend=bayes.trend)
      } else {
        fit <- edgeR::glmFit(d2, design, dispersion=d2[[disp]])
      }
      return(list(d=d, d2=d2, fit=fit))
    }
  }



#' Helper function to generate an output table with only most relevant columns
#' @param contrast Character; a contrast group name pair in the typical format, i.e., "group2-group1"
#' @param annotated.normcnt data frame; annotated output table generated by performing pair-wise comparisons and
#'   corresponding statistical tests. From this the normalised counts are extracted.
#' @param samp.name.and.group.key \code{data.frame}. Sample names (matching with annotated.normcnt cols) as rownames, groups in 1st column
#' @param out.dir Character; output directory for final tables.
#' @param samp.name.and.group.key Factor of sample names.
#' @param analysis.name Character used in the output file name.
#' @param filtered.lists Logical; should the DGE table be filtered before saving it to a file?
#' @param fdr.thr Numeric; the FDR threshold for filtering.
#' @param logfc.thr Numeric; the fold-change threshold on the log2-scale for filtering.
#' @export
diffr_expr_generate_cleaned_de_table_output <-
  function(contrast, annotated.normcnt, out.dir=".", samp.name.and.group.key, analysis.name=NULL, filtered.lists = TRUE,  fdr.thr=0.05, logfc.thr=1 )
  {
    cat("Generating a cleaned version of expression table...\n")
    DE.out <- paste(analysis.name, contrast, "differential_expression_clean.tsv", sep="_")

    group1 <- unlist(strsplit(contrast, split="-",fixed = TRUE))[1]
    group2 <- unlist(strsplit(contrast, split="-",fixed = TRUE))[2]

    contrast.samples <- rownames(samp.name.and.group.key)[samp.name.and.group.key$group == group1 | samp.name.and.group.key$group == group2]
    not.contrast.samples <- rownames(samp.name.and.group.key)[!(samp.name.and.group.key$group == group1 | samp.name.and.group.key$group == group2)]

    annotated.normcnt <- annotated.normcnt[,!colnames(annotated.normcnt) %in% not.contrast.samples]

    cleaned.colnames <- gsub("ReadsPerGene.out", "", colnames(annotated.normcnt))
    #print(cleaned.colnames)
    colnames(annotated.normcnt) <- cleaned.colnames
    cat("   Samples outside the contrast were removed...\n")

    if (filtered.lists) {
      cat("     Filtering the DE list to be saved by fdr <", fdr.thr, "and logfc >= ", logfc.thr , "...\n")
      fdr.col <- names(annotated.normcnt)[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(annotated.normcnt)))]
      fc.col <- names(annotated.normcnt)[grep("^logfc$|fold$", tolower(names(annotated.normcnt)))]

      #print(fdr.col)
      #print(fc.col)

      nrow.before.filtering <- nrow(annotated.normcnt)

      annotated.normcnt <- annotated.normcnt[(annotated.normcnt[[fdr.col]] < fdr.thr &
                                                abs(annotated.normcnt[[fc.col]]) >= logfc.thr),]

      nrow.removed <- nrow.before.filtering - nrow(annotated.normcnt)
      cat("       ", nrow.removed, "unsignifcant genes were filtered out...\n")
      cat("        The dimensions of the table to be saved:", dim(annotated.normcnt), "...\n")


      DE.out <- paste("filtered", DE.out, sep="_")
    }

    cat("   Saving cleanded DE-list to", DE.out, "...\n")
    write.table(annotated.normcnt, file.path(out.dir, DE.out), sep="\t", quote=FALSE, row.names=FALSE)

  }

#' Function to extract contrasts and generate top tables and plots
#' @param contrasts Contrast matrix as generated by \code{makeContrasts()}. If \code{NULL}, the default, the design matrix
#'   is expected to describe simple pair-wise comparisons, i.e., with the contrasts already included in the matrix.
#'   Consequently, in that case, no contrasts will be fitted.
#' @param fit An MArrayLM object produced by \code{lmFit}.
#' @param fit2 An MArrayLM object produced by \code{eBayes}.
#' @param normcnt Matrix; depth-adjusted reads per million or "voomed" counts, i.e., a numeric matrix of
#'   normalized expression values on the log2 scale.
#' @param do.voom Logical; should data be "voomed"?
#' @param quasi.likelihood Logical; should quasi-likelihood methods be used? See \emph{Details} section.
#'   If \code{TRUE}, the default, then the quasi-likelihood methods are used, if \code{FALSE}, then the
#'   likelihood ratio test is used. Olease note the main wrapper function \code{diffExpr()} will set this parameter.
#' @param out.l List; list of result objects generated upstream iin the workflow to add output from this function to.
#' @param out.dir Character; output directory for final tables.
#' @param analysis.name Character used in the output file name.
#' @param biomart Logical; should biomart annotation be added?
#' @param biom.data.set \code{character} of length one. Biomart data set to use.
#' @param biom.mart \code{character} vector. Biomart to use (uses the first element of the vector), defaults to "ensembl".
#' @param host \code{character} of length one. Host URL.
#' @param biom.filter \code{character} of length one. Name of biomart filter, i.e., type of query ids, defaults to "ensembl_gene_id".
#' @param biom.attributes \code{character} vector. Biomart attributes, i.e., type of desired result(s); make sure query id type is included!
#' @param biom.cache \code{character}. Path name giving the location of the cache \command{getBM()} uses if \code{use.cache=TRUE}. Defaults to the value in the \emph{BIOMART_CACHE} environment variable.
#' @param use.cache (\code{logical}). Should \command{getBM()} use the cache? Defaults to \code{TRUE} as in the \command{getBM()} function and is passed on to that.
#' @param sym.col \code{character}. Name of the column in the query result with gene symbols.
#' @param rm.dups \code{logical}. Should duplicated input IDs (\option{biom.filter}) be removed from the result?
#' @param p.thr Numeric; P-Value threshold used in plots.
#' @param fdr.thr Numeric; FDR threshold used in plots and for generating cleaned output tables.
#' @param logfc.thr Numeric; FC threshold on the log2-scale used in plots and for generating cleaned output tables.
#' @param numlab \code{numeric}. Maximum number of labels per plot. Overrides numbers calculated based on `p.thr` and `fdr.thr`.
#' @param point.lab \code{logical}. Should points be labelled, at all?
#' @param heatmap.topn \code{numeric}. Number of top values to be plotted. Defaults to 100.
#' @param heatmap.split.expr \code{logical}. Should the top up- and top down-regulated genes be displayed at equal numbers (50/50),
#' if they meet the significance threshold (regardless of the actual significance)? Defaults to \code{FALSE}.
#' @param font.size Size of point labels in M-A plots.
#' @param plots Logical; should plots be generated?
#' @param lists Logical; should output tables be written to files?
#' @param filtered.lists Logical; should the DGE table be filtered before saving it to a file?
#' @param samp.info \code{data.frame}. \code{samp.info} object containing information of the project's sample sheet.
#' @param samples \code{character}. Name of the column in 'samp.info' containing sample names. If 'samp.info' is not supplied
#'     vector of sample names.
#' @param groups \code{character}. Name of the column in 'samp.info' containing grouping information. If 'samp.info' is not supplied
#'     vector of groups.
#' @param sample.plot.names \code{character}. Optional name of a column with "nice" sample names for plotting.
#' @export
diff_expr_extract_contrasts <-
  function(contrasts=NULL, fit, fit2=NULL, normcnt, out.l, do.voom=TRUE, quasi.likelihood=TRUE, out.dir=".",
           analysis.name=NULL, biomart=FALSE, biom.data.set="hsapiens_gene_ensembl", biom.mart=c("ensembl", "snp", "funcgen", "vega", "pride", "plants"),
           host="https://www.ensembl.org", biom.filter="ensembl_gene_id", biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"),
           biom.cache = NULL, use.cache = FALSE, sym.col="hgnc_symbol",
           rm.dups=FALSE, p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, point.lab=TRUE, heatmap.topn = 100,
           heatmap.split.expr = FALSE, font.size=5, plots=TRUE, lists=TRUE, filtered.lists = TRUE,
           samp.info = NULL, samples = NULL, groups = NULL, sample.plot.names = NULL)
  {
    # initial checks
    if (is.null(samp.info)) stop("Need sample sheet! Provide as data frame to 'samp.info' argument.")
    if (is.null(samples)) stop("Need name of column in sample sheet containing sample names!")
    if (is.null(groups)) stop("Need name of column in sample sheet containing grouping information!")
    if (is.null(analysis.name)) {
      analysis.name <- paste0(paste(levels(groups)[1:2], collapse="_"), "_")
      cat("Using default settings for the 'analysis name':", sQuote(analysis.name), "\n")
      warning("A unique and descriptive name for the analysis should always be provided!")
    }

    if (!length(grep("contrasts", names(out.l)))) {
      out.l$contrasts <- list()
    }
    if (is.null(contrasts)) {
      cat("  Extracting 'groups' levels from design...\n")
      cn <- grep("^groups.+", colnames(fit$design), value=TRUE)
    } else if (is.matrix(contrasts) && !is.null(colnames(contrasts))) {
      # if do.voom=TRUE contrasts have been calculated already in the fit wrapper function above and only need to be extracted
      # in the case of paired samples, contrasts are inherent to the design and only need to be extracted, i.e., we provide the coefficient of interest to the test function.
      # For GL models, we need to feed the contrast of interest in form of a matrix to glmLRT or glmQLFTest to instruct it to calculate the desired contrasts before doing the test
      # see the different behaviour of glmLRT/glmQLFTest below for do.voom=FALSE
      cn <- colnames(contrasts)
    } else {
      # contrasts is a character vector
      # this will only be called for the non-contrasted columns of the design matrix for paired samples
      # which means contrasts are inherent to the design and only need to be extracted
      cn <- contrasts
    }

    out.l$MAplots <- list()
    out.l$volcanoPlots <- list()
    for (contr in cn) {
      cat("Calculating differential expression for", contr, "\n")
      dir.create(file.path(out.dir, contr))
      contr.out.dir  <- dir(out.dir, pattern = paste0("^",contr), full.names = TRUE)
      cat("Storing all results under", contr.out.dir, "\n")

      if (do.voom) {
        if (is.null(fit2)) stop("Need 'fit2' object!")
        cat("Generating output table of differentially expressed features...\n")
        tt <- limma::topTable(fit2, coef=contr, number=nrow(fit2), sort.by="P")
      } else {
        test.fun <- ifelse(quasi.likelihood, edgeR::glmQLFTest, edgeR::glmLRT)
        # Perform a likelihood ratio test or a quasi-likelihood F-Test, specifying the contrast of interest.
        # Needs to be done per-contrast as otherwise it will perform the LR test of all contrasts together while we want this done individually.
        cat("Performing likelihood ratio test on this contrast...\n")
        if (is.matrix(contrasts)) {
          # calculating the contrast
          de <- test.fun(fit, contrast = contrasts[, contr])
        } else {
          # only extracting the contrast (for paired samples)
          de <- test.fun(fit, coef=contr)
        }
        # Use the topTags function to present a tabular summary of the differential expression statistics (note that topTags
        # operates on the output of exactTest or glmLRT, but only the latter is shown here)
        cat("Generating tablular summary of differential expression statistics ('top table')\n")
        tt <- edgeR::topTags(de, n = nrow(de))
        #			} else {
        #				stop("Need contrast matrix as input.")
        #			}
      }
      if (is.null(contrasts)) {
        fitcnt <- fit$coefficients[, contr]
        addinfo <- cbind(normcnt, fitcnt)
        if (do.voom) {
          names(addinfo)[names(addinfo) %in% "fitcnt"] <- "Fitted Coefficients (log2)"
        } else {
          names(addinfo)[names(addinfo) %in% "fitcnt"] <- "Fitted Coefficients (ln)"
        }
      } else if (is.matrix(contrasts)) {
        fitcnt <- fit$coefficients[, rownames(contrasts)[contrasts[, contr]!=0]]
        addinfo <- cbind(normcnt, fitcnt)
      } else {
        addinfo <- normcnt
      }
      d3 <- merge(addinfo, tt, by="row.names", sort=FALSE)
      cat("Renaming ID column...\n")
      names(d3)[1] <- "ID"
      if (biomart) {
        d3 <- diff_expr_biomart(d3, biom.data.set, biom.mart, host, biom.filter, biom.attributes, biom.cache, use.cache, sym.col, rm.dups)
        id.col <- names(d3)[names(d3) %in% biom.filter]
      } else {
        syms <- convertid::convertId2(as.character(d3$ID))
        syms <- data.frame(ID=names(syms), gene_symbol=as.character(syms), stringsAsFactors=FALSE)
        d3 <- merge(syms, d3, by="ID", all.y=TRUE, all.x=FALSE, sort=TRUE)
        if (any(d3$gene_symbol=="") || any(is.na(d3$gene_symbol))) {
          cat("  Replacing", length(which(d3$gene_symbol=="" | is.na(d3$gene_symbol))), "missing Gene Symbols by Ensembl IDs...\n")
          d3$gene_symbol[d3$gene_symbol=="" | is.na(d3$gene_symbol)] <- as.character(d3$ID[d3$gene_symbol=="" | is.na(d3$gene_symbol)])
        }
        id.col <- "ID"
      }
      cat("Setting unique row names...\n")
      rownames(d3) <- make.unique(as.character(d3[[id.col]]))
      out.l$contrasts[[contr]] <- d3
      if (lists) {
        DE.out <- paste(analysis.name, contr, "differential_expression.tsv", sep="_")
        cat("Saving list to", DE.out, "...\n")
        pv.col <- names(d3)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
        cat("The result table is ordered in increasing order by column ", pv.col, "...\n")
        d3 = d3[order(d3[[pv.col]]),]
        write.table(d3, file.path(contr.out.dir, DE.out), sep="\t", quote=FALSE, row.names=FALSE)

        diffr_expr_generate_cleaned_de_table_output(contrast=contr, annotated.normcnt=d3, samp.name.and.group.key = fit$samples, out.dir=contr.out.dir,
                                                    analysis.name, filtered.lists = TRUE, fdr.thr=fdr.thr, logfc.thr=logfc.thr)
      }

      # Create a graphical summary, such as an M (log-fold change) versus A (log-average expression) plot, here showing the
      # genes selected as differentially expressed (with a 5% false discovery rate)
      if (plots) {
        cat("Plotting...\n")
        pdf(file.path(contr.out.dir, paste(analysis.name, contr, "_plots.pdf", sep="_")), width = 15, height = 15)
        par(mar = c(6,6,5,3))
        cat(" MA-plot...\n")
        out.l$MAplots[[contr]] <- diff_expr_ma_plot(d3, contr, id.col, sym.col, p.thr, fdr.thr, logfc.thr, numlab, out.dir=contr.out.dir, analysis.name, point.lab, biom.attributes, font.size, lists)

        ## Volcano plot
        cat(" Volcano plot...\n")
        #The following three lines would probably be wise to do using regular expression
        volcano.name = gsub(".", " ", contr, fixed=TRUE)
        volcano.name = gsub("_", " ", volcano.name, fixed=TRUE)
        volcano.name = gsub("-", " vs. ", volcano.name, fixed=TRUE)
        out.l$volcanoPlots[[contr]] <- diff_expr_volcano_plot(d3, id.col, sym.col="gene_symbol", main=volcano.name, p.thr=p.thr, fdr.thr=fdr.thr, logfc.thr=logfc.thr, numlab=numlab, point.lab=point.lab)

        #png(paste(out.dir,"/",analysis.name,".Pvalue_distribution.png",sep=""),width=1280,height=960,res=150)
        ## Histogram of P-value distribution
        cat(" Dendrogram plot...\n")
        diff_expr_pval_hist_plot(d3)

        cat("Heatmap plots...\n")
        out.l$heatmapPlots[[contr]] <- pheatmap_plots(d3, id, sym.col="gene_symbol", samp.info = samp.info, samples, groups, sample.plot.names = sample.plot.names, main=NULL,
                                                      p.thr=0.05, fdr.thr=0.05, logfc.thr = 1, topn = heatmap.topn, split.expr = heatmap.split.expr)
        #print(class(out.l$heatmapPlots[[contr]]))
        dev.off()
      }
    }
    cat("=============================================================================\n")
    cat("Venn sections list\n")
    cols.interest.de.table = c("ensembl","symbol|hgnc","description","entrez","^average$|^ave[a-r]{0,4}expr[e-s]{0,6}$","^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$","^p\\.{0,1}val[e-u]{0,2}$")
    pv.col = names(out.l$contrasts[[1]])[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(out.l$contrasts[[1]])))]
    fdr.col = names(out.l$contrasts[[1]])[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(out.l$contrasts[[1]])))]

    sign.de.tables <- lapply(out.l$contrasts, function(x) {
      sel.col.de.table <- names(x)[grep(paste(cols.interest.de.table,collapse="|"), tolower(names(x)))]
      new.de.table <- x %>% dplyr::select(sel.col.de.table)
      return(new.de.table)
    })

    join.interest <- paste(c("ensembl", "symbol|hgnc", "description", "entrez"), collapse = "|")
    join.vec <- grep(join.interest, tolower(names(out.l$contrasts[[1]])), value = T)

    if (all(lapply(sign.de.tables, function(x) nrow(x[x[[fdr.col]] < 0.05,])) > 0)) {
      sign.de.tables = lapply(sign.de.tables, function(x) x[x[[fdr.col]] < 0.05,])
    } else {
      sign.de.tables = lapply(sign.de.tables, function(x) x[x[[pv.col]] < 0.05,])
    }

    # v = list with the venn.diagram plot and all venn sections tables
    v <- diffr_venn(list.comp.tables = sign.de.tables,join.vec = join.vec)
    #print(class(v))

    if (plots && !is(v[["venn.diagram"]], "try-error")) {
      cat(">>> Plotting Venn diagram...")
      pdf(file.path(out.dir,"Venn_Diagram.pdf"), width = 15, height= 15)
      grid::grid.draw(v[["venn.diagram"]])
      dev.off()
      cat("done\n")
    }
    #browser()
    ifelse(!dir.exists(file.path(out.dir, "Venn sections")), dir.create(file.path(out.dir, "Venn sections")), FALSE)
    for(j in 1:length(v[["venn.sections"]])){
      print(names(v[["venn.sections"]])[j])
      openxlsx::write.xlsx(v[["venn.sections"]][[j]], file = file.path(out.dir, "Venn sections", paste0(names(v[["venn.sections"]])[j],".xlsx")))
    }
    print("Venn sections list end")
    cat("done\n")
    return(out.l)
  }

#' Function to retrieve additional information from biomart
#' @param d3 data frame to be annotated with biomart; annotated output table generated by performing pair-wise comparisons and
#'   corresponding statistical tests.
#' @param biom.data.set \code{character} of length one. Biomart data set to use.
#' @param biom.mart \code{character} vector. Biomart to use (uses the first element of the vector), defaults to "ensembl".
#' @param host \code{character} of length one. Host URL.
#' @param biom.filter \code{character} of length one. Name of biomart filter, i.e., type of query ids, defaults to "ensembl_gene_id".
#' @param biom.attributes \code{character} vector. Biomart attributes, i.e., type of desired result(s); make sure query id type is included!
#' @param biom.cache \code{character}. Path name giving the location of the cache \command{getBM()} uses if \code{use.cache=TRUE}. Defaults to the value in the \emph{BIOMART_CACHE} environment variable.
#' @param use.cache (\code{logical}). Should \command{getBM()} use the cache? Defaults to \code{TRUE} as in the \command{getBM()} function and is passed on to that.
#' @param sym.col \code{character}. Name of the column in the query result with gene symbols.
#' @param rm.dups \code{logical}. Should duplicated input IDs (\option{biom.filter}) be removed from the result?
#' @export
diff_expr_biomart <-
  function(d3, biom.data.set="hsapiens_gene_ensembl", biom.mart=c("ensembl", "snp", "funcgen", "vega", "pride", "plants"),
           host="https://www.ensembl.org", biom.filter="ensembl_gene_id", biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"),
           biom.cache = NULL, use.cache = FALSE, sym.col="hgnc_symbol", rm.dups=FALSE)
  {
    # test if needed packages are installed
    if (use.cache && !requireNamespace("rappdirs", quietly = TRUE)) {
      stop(
        paste("Package", sQuote("rappdirs"), "must be installed to use the biomart cache."),
        call. = FALSE
      )
    }
    if (use.cache && is.null(biom.cache)) {
      biom.cache <- rappdirs::user_cache_dir("biomaRt")
    }
    gene.lab <- convertid::convert.bm(d3, "ID", biom.data.set, biom.mart, host, biom.filter, biom.attributes, biom.cache, use.cache, sym.col, rm.dups)
    names(gene.lab)[names(gene.lab)==sym.col] <- "gene_symbol"
    cat("  Extended annotation:\n")
    biom.attributes[biom.attributes==sym.col] <- "gene_symbol"
    if (length(d3$ID)>8) {
      print(gene.lab[1:8, biom.attributes])
      cat("_truncated_ (", length(d3$ID), "features)\n")
    } else {
      print(gene.lab[, biom.attributes])
    }
    return(gene.lab)
  }


