# Differential expression analysis of RNA-Seq data
#
# mRNA expression
# miRNA expression
#
# INPUT:   count files generated by HTSeq for mRNA sequencing data
#          miRNA expression table file from CAP-miRSEQ expression_reports.sh output [mature_miRNA_expression.xls]
#
# OUTPUT:  multiple tables and plots
#
# AUTHOR:  Vidal Fey <vidal.fey@utu.fi>
# DATE:    27 August 2015


############################################################################
## miRNA expression part:
##
## # USAGE: differential_expression.R <Mature_miRNA_expression.xls> <output dir> <analysis name> <samples (s1,s2)> <groups (g1,g2)> <pairs (optional)>
##
## Description:
## R script to calculate the differential expression of miRNA using edgeR
##
## Author: Jared Evans
## Date: 5/22/14
## Modified: Vidal Fey, 150827
##
## Parameters:
## <expr.file> - character, name of miRNA expression table file from CAP-miRSEQ expression_reports.sh output [mature_miRNA_expression.xls]
## <out.dir> - Directory where differential expression results should be written to
## <analysis.name> - unique identifier for this analysis that will be prepended to output filenames
## <samples)> - character vector of sample names
## <groups> - character vector of groups the above samples belong to (in the same order as samples)
## <pairs> - Optional character vector of names indicating how samples are paired ie timepoint1 and timepoint2 of same sample
##
############################################################################

#' @title Differential expression analysis of RNA-Seq data
#' @docType package
#' @name diffr
#' @description This package provides functionality for differential expression analysis of read counts from mRNA sequencing data or miRNA expression values
#' generated by the CAP-miRSEQ 'expression_reports.sh' script. The workflow follows the 'edgeR'-'limma' expression data analysis pipeline providing options
#' for different approaches, such as "pure" 'edgeR', 'voom' or paired samples. The functions in the package generate text files with differential expression lists,
#' optionally annotated with information from 'biomart', expression summary plots as well as several QC plots.
#' @author Vidal Fey <vidal.fey@geneviatechnologies.com>
#' Maintainer: Vidal Fey <vidal.fey@geneviatechnologies.com>
#' @details \tabular{ll}{
#' Package: \tab diffr\cr
#' Type: \tab Package\cr
#' Initial version: \tab 0.1-0\cr
#' Created: \tab 2015-08-27\cr
#' License: \tab to be determined \cr
#' LazyLoad: \tab yes\cr
#' }
#' The package contains utilities and methods for differential expression analysis of RNA-Seq data.
#' It comes with a wrapper function, "diffExpr", performing all steps of the analysis. Most sub-functions are exported and can be called by the user, as well, if desired.
#' These functions may be applicable to different kinds of data/input, rely, however, on the conventions set for this package.
#' @keywords package
#' @import medseqr
#' @import plyr
#' @import edgeR
#' @import limma
#' @import RColorBrewer
#' @import ggplot2
#' @import ggrepel
#' @import biomaRt
#' @import maptools
#' @import scatterplot3d
#' @import dendextend
#' @importFrom genefilter rowVars
NULL
#'
#' Main wrapper for executing the entire pipeline from reading in expression data such as count
#' files to producing text files and graphs
#' @description \command{diffExpr} is a conveniency wrapper performing all steps automatically.
#'    Most sub-functions are exported and can be called by the user, as well, if desired.
#'    These functions may be applicable to different kinds of data/input, rely, however,
#'    on the conventions set for this package.
#' @param expr.file \code{character}. Vector of input file paths
#' @param samp.info \code{data.frame}. samp.info object containing information of the project's sample sheet
#' @param control \code{character}. Name of the control group
#' @param design \code{matrix}. design matrix
#' @param samples \code{character}. Name of the column in 'samp.info' containing sample names. If 'samp.info' is not supplied
#'     vector of sample names.
#' @param sample.plot.names \code{character}. Optional name of a column with "nice" sample names for plotting.
#' @param groups \code{character}. Name of the column in 'samp.info' containing grouping information. If 'samp.info' is not supplied
#'     vector of groups.
#' @param pairs \code{character}. Name of the column in 'samp.info' containing paired sample information.
#' @param block \code{logical}. Are the comparisons to be made within AND between subjects? See Details section.
#' @param bayes.trend \code{logical}. Should an intensity-trend be allowed for the prior variance? Passed to 'limma::eBayes'.
#' @param bayes.robust \code{logical}. Should the estimation of df.prior and var.prior be robustified against outlier sample variances? Passed to 'limma::eBayes'.
#' @param sym.col \code{character}. Name of the column in the query result with gene symbols
#'
#' @details For experiemtal desgins involving comparisons within as well as between subjects inter-subject needs to be computed.
#'     In this case, the column specified in the 'pairs' argument must assign the subjects to the treatment/tissue/etc groups.
#'     For example, if we have two treatments the effects of which are to be observed in each two tissues, this design would apply.
#'     The 'pairs' factor is passed to the functions 'duplicateCorrelation' and 'lmFit'.
#' @return A list of all relevant objects generated in the course of the workflow:
#' \itemize{
#'   \item if `voom=TRUE`, voomed counts, otherwise DGEList object with TMM-normalisation factors
#'   \item if `voom=TRUE`, lmFit object, otherwise DGEList object with estimated dispersion
#'   \item if `voom=TRUE`, eBayes output of contrasted groups, otherwise glmFit object
#'   \item annotated topTable/topTags output
#' }
#' However, the function is first and foremost called for its side effects of generating results tables and plots.
#'
#' @export
diffExpr <-
		function(expr.file="mature_miRNA_expression.xls", samp.info, control, design=NULL, samples=NULL, sample.plot.names=NULL, groups=NULL, pairs=NULL, block=FALSE, contrasts=NULL, out.dir=NULL,
				analysis.name=NULL, biomart=FALSE, biom.data.set="hsapiens_gene_ensembl", biom.mart=c("ensembl", "snp", "funcgen", "vega", "pride", "plants"),
				host="www.ensembl.org", biom.filter="ensembl_gene_id", biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"), sym.col="hgnc_symbol",
				rm.dups=FALSE, p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, point.lab=TRUE, min.samp=NULL, strict = TRUE, disp=c("gene", "trend", "common"), do.voom=FALSE,
				voom.fun=voom, norm.method=c("tmm", "quantile"), bayes.trend=FALSE, bayes.robust=FALSE, n=500, gene.selection="common", ellipse=TRUE,
				circle=TRUE, varname.size=0, var.axes=FALSE, samp.lab=TRUE, PC=c(1,2,3), type=c("both", "uncorrected", "pseudo-corrected"), font.size=5,
				plots=TRUE, lists=TRUE)
{
	## initial checks
	if (missing(expr.file) || !is.character(unlist(expr.file))) {
		stop("Need input file with raw expression values (read counts)!")
	}
	if (missing(samp.info)) {
		if (is.null(samples)) {
			stop("Need sample names!")
		}
		if (length(samples) == 1) {
			stop("Need more than 1 sample name!")
		}
		if (is.null(groups)) {
			stop("Need groups!")
		}
		if (length(groups) == 1) {
			stop("Need more than 1 groups!")
		}
	} else {
		if (is.null(samples) || length(samples) > 1) {
			stop("Need name of colum containing sample names!")
		}
		if (is.null(groups) || length(groups) > 1) {
			stop("Need name of colum containing groupings!")
		}
		if (!is.data.frame(samp.info)) {
			stop("'samp.info' needs to be a data.frame object containing at least two columns: 'SampleNames' and 'Groups' (the actual names can be provided\nby the 'samples' and 'groups' arguments, repsectively.)")
		}
	}
	
	if (block) {
		do.voom <- TRUE
		cat("*** Using 'blocked' design (i.e., samples are measured _in blocks_). Enforcing 'voom'! ***\n")
	}

	## switch off plotting device on exit
	on.exit({plyr::l_ply(dev.list(), dev.off)})

	## enforce voom for paired samples
#	if (!is.null(pairs)) {
#		cat("Samples are paired! Enforcing 'voom'\n")
#		do.voom <- TRUE
#	}
#
	## standardize samp.info
	### needs to be a data.frame with (at least) two columns: 'SampleNames' and 'Groups'
	### if a data.frame is provided by the 'samp.info' argument the columns are renamed to meet that convention
	#### save Groups name first
	grp.nam <- groups
	#### reformat samp.info data frame
	samp.info <- diff_expr_get_samp_info(samp.info, samples, groups)

	## make control group first levels to ensure it becomes the '(Intercept)'
	cat("  Setting control group...\n")
	if (is.numeric(samp.info$Groups)) {
		control <- paste0("group_", control)
	}
	groups <- relevel(samp.info$Groups, ref=control)

	if (is.null(analysis.name)) {
		analysis.name <- paste0(paste(levels(groups)[1:2], collapse="_"), "_")
		cat("Using default settings for the 'analysis name':", sQuote(analysis.name), "\n")
		warning("A unique and descriptive name for the analysis should always be provided!")
	}

	## read counts
	counts <- diff_expr_read_counts(expr.file, samp.info)

	## Filter weakly expressed and noninformative (e.g., non-aligned) features
	cat("Filtering...\n")
	counts <- diff_expr_filter_counts(counts, samp.info, strict, min.samp)

	## Create a DGEList object (edgeR’s container for RNA-seq count data)
	d <- DGEList(counts = counts, group = groups)
	## Estimate normalization factors
	d <- calcNormFactors(d)
	## Inspect the relationships between samples using a multidimensional scaling (MDS) plot
	if (plots) {
		if (!is.null(sample.plot.names)) {
			spn <- samp.info[, c("SampleNames", sample.plot.names)]
			spn <- spn[match(colnames(d), spn$SampleNames), ]
			if (identical(as.character(spn$SampleNames), colnames(d))) {
				sample.plot.names <- as.character(spn[, sample.plot.names])
			}
		}
		diff_expr_mds_plot(d, groups=groups, n=n, sample.plot.names=sample.plot.names, analysis.name=analysis.name, do.pdf=TRUE, out.dir=out.dir)
	}

	# create design matrix
	if (is.null(design)) {
		design <- diff_expr_make_design(samp.info, groups, pairs, block)
	} else {
		grp.col <- grep(paste0("^", grp.name), colnames(design))
		if (length(grp.col)) {
			colnames(design)[grp.col] <- sub(paste0("^", grp.name), "groups", colnames(design)[grp.col])
		}
	}
	if (length(grep(":", colnames(design)))) {
		cat("  Checking design column names...\n")
		colnames(design) <- gsub(":", "__", colnames(design))
	}

	## set contrasts
	contrasts <- diff_expr_make_contrasts(design, pairs, block, contrasts)

	## set dispersion method
	disp <- match.arg(disp)
	disp <- switch(disp, gene="tagwise.dispersion", trend="trended.dispersion", common="bin.dispersion")

	## extract 'pairs' factor from 'samp.info' and keep column name in 'pairs_col' variable
	if (!is.null(pairs)) {
		pairs_col <- pairs
		pairs <- samp.info[[pairs]]
	}
	
	## voom
	if (do.voom) {
		cat("Running 'voom'...\n")
		norm.method <- match.arg(norm.method)
		vf <- match.call()$voom.fun
		cat("  Running", sQuote(vf), "with", norm.method, "normalisation...\n")
		## compute linear model fit and optionally apply voom beforehand
		#### NOTE: voom generates log2-cpms

		fit.l <- diff_expr_fit(counts, d, design, do.voom=TRUE, voom.fun, norm.method, bayes.trend, bayes.robust, pairs, pairs_col, block, contrasts)

		out.l <- list(v=fit.l$v, fit=fit.l$fit, fit2=fit.l$fit2)
		if (!block && !is.null(pairs)) {
			cat("    Paired samples: additional eBayes on first fit object...\n")
			fit3 <- eBayes(fit.l$fit, trend = bayes.trend, robust = bayes.robust)
			out.l$fit3 <- fit.l$fit3
		}
		normcnt <- fit.l$v$E
	} else {
		fit.l <- diff_expr_fit(counts, d, design, do.voom=FALSE, bayes.trend=bayes.trend, bayes.robust=bayes.robust, disp=disp)
		out.l <- list(d=fit.l$d, d2=fit.l$d2, fit=fit.l$fit)
		# normalized expression
		# Get the depth-adjusted reads per million
		cat("Generating output table of differentially expressed features...\n")
		normcnt <- cpm(fit.l$d2, normalized.lib.sizes=TRUE, log=TRUE, prior.count=3)
	}

	type <- match.arg(type)
	if (type=="both") {
		cat("Plotting both uncorrected and pseudo-corrected if applicable...\n")
	}
	if (plots) {
		if (type %in% c("both", "uncorrected")) {
			## quality control plots for uncorrected data
			cat("Quality control plots...\n")
			cat("  Uncorrected, normalised data...\n")
			if (do.voom) {
				type.plot <- "uncorrected, normalised voom output"
			} else {
				type.plot <- "uncorrected, normalised DGEList"
			}
			out.l <- diff_expr_QC_plots(counts=normcnt, samp.info=samp.info, control=control, out.l=out.l, grp.nam=grp.nam, PC=PC, ellipse=ellipse, circle=circle, varname.size=varname.size,
					var.axes=var.axes, samp.lab=samp.lab, pairs=pairs, pairs.name=pairs_col, gene.selection=gene.selection, n=n, type=type.plot, analysis.name=analysis.name, out.dir=out.dir)
		}

		if (!block && !is.null(pairs) && (type %in% c("both", "pseudo-corrected"))) {
			## quality control plots for pseudo-corrected data
			cat("  Corrected, normalised pseudo-counts...\n")
			## get pseudo counts for blocked designs (e.g., paired samples or batch factors)
			cat("   Calculating pseudo-counts...\n")
			pseudo.counts <- diff_expr_pseudo_counts(design=design, d=d, pairs=pairs, disp=disp, do.cpm=TRUE)
			cat("   done\n")
			out.l <- diff_expr_QC_plots(counts=pseudo.counts, samp.info=samp.info, control=control, out.l=out.l, grp.nam=grp.nam, PC=PC, ellipse=ellipse, circle=circle, varname.size=varname.size,
					var.axes=var.axes, samp.lab=samp.lab, pairs=pairs, pairs.name=pairs_col, gene.selection=gene.selection, n=n, type="pseudo-corrected, normalised DGEList", analysis.name=analysis.name, out.dir=out.dir)
		}
	}

	cat("Extracting contrasts...\n")
	if (do.voom) {
		if (!block && !is.null(pairs)) {
			cat("  ...for paired samples comparisons (voom)...\n")
			cont <- grep("^groups.+", colnames(fit3$coefficients), value=TRUE)
			cat("  ", cont, "\n")
			out.l <- diff_expr_extract_contrasts(cont, fit.l$fit, fit3, normcnt, out.l, do.voom=TRUE, out.dir, analysis.name, biomart, biom.data.set, biom.mart,
					host, biom.filter, biom.attributes, sym.col, rm.dups, p.thr, fdr.thr, logfc.thr, numlab, point.lab, font.size, plots, lists)
		}
		if (!is.null(contrasts)) {
			cat("  ...for all (remaining) comparisons (voom)...\n")
			out.l <- diff_expr_extract_contrasts(contrasts, fit.l$fit, fit.l$fit2, normcnt, out.l, do.voom=TRUE, out.dir, analysis.name, biomart, biom.data.set, biom.mart,
					host, biom.filter, biom.attributes, sym.col, rm.dups, p.thr, fdr.thr, logfc.thr, numlab, point.lab, font.size, plots, lists)
		}
	} else {
		if (!is.null(pairs)) {
			cat("  ...for paired samples comparisons (GLM)...\n")
			cont <- grep("^groups.+", colnames(fit$coefficients), value=TRUE)
			cat("  ", cont, "\n")
			out.l <- diff_expr_extract_contrasts(cont, fit.l$fit, NULL, normcnt, out.l, do.voom=FALSE, out.dir, analysis.name, biomart, biom.data.set, biom.mart,
					host, biom.filter, biom.attributes, sym.col, rm.dups, p.thr, fdr.thr, logfc.thr, numlab, point.lab, font.size, plots, lists)
		}
		if (!is.null(contrasts)) {
			cat("  ...for all (remaining) comparisons (GLM)...\n")
			out.l <- diff_expr_extract_contrasts(contrasts, fit.l$fit, NULL, normcnt, out.l, do.voom=FALSE, out.dir, analysis.name, biomart, biom.data.set, biom.mart,
					host, biom.filter, biom.attributes, sym.col, rm.dups, p.thr, fdr.thr, logfc.thr, numlab, point.lab, font.size, plots, lists)
		}
	}
	on.exit()
	return(out.l)
}

#' Function to standardize `samp.info` sample information data frame
#' @export
diff_expr_get_samp_info <-
		function(samp.info, samples, groups)
{
	if (!is.null(samp.info)) {
		cat("Using user-provided sample information...\n")
		cat("  Renaming sample name column...\n")
		names(samp.info)[names(samp.info) == samples] <- "SampleNames"
		cat("  Renaming groups column...\n")
		names(samp.info)[names(samp.info) == groups] <- "Groups"
		cat("  Factorizing columns... \n")
		samp.info$SampleNames <- dropEmptyLevels(as.factor(samp.info$SampleNames))
		samp.info$Groups <- dropEmptyLevels(as.factor(samp.info$Groups))
	} else {
		samp.info <- data.frame(SampleNames=samples, Groups=groups)
	}
	if (is.numeric(samp.info$Groups)) {
		samp.info$Groups <- paste0("group_", samp.info$Groups)
	}
	cat("  Reordering by sample names...\n")
	samp.info <- samp.info[order(samp.info$SampleNames), ]
	return(samp.info)
}

#' Function to read counts as produced by htseq-count
#' @export
diff_expr_read_counts <-
		function(expr.file, samp.info)
{
	if (length(unlist(expr.file)) > 1) {
		## check sample names
		cat("Checking expression file names...\n")
		if (is.null(names(expr.file))) {
			names(expr.file) <- sub("\\.[a-z]{1,5}$", "", basename(expr.file))
		}
		expr.file <- expr.file[order(names(expr.file))]
		if (any(names(expr.file) %in% samp.info$SampleNames)) {
			snam <- which(names(expr.file) %in% samp.info$SampleNames)
			if (!identical(names(expr.file)[snam], as.character(samp.info$SampleNames))) {
				stop("Input vector of count file names must be identical to all or a subset of sample names provided in 'samp.info', i.e., it must be the same names in the same order!")
			} else {
				if (nrow(samp.info) < length(expr.file)) {
					cat("  Importing subset of samples...\n")
				}
				expr.file <- expr.file[as.character(samp.info$SampleNames)]
			}
		} else {
			stop("Sample names not found in input files")
		}
		# import individual count files
		cat("Reading count files for samples:\n")
		print(samp.info$SampleNames)
		counts <- readDGE(expr.file)$counts
	} else {
		# reading output from CAP-miRSEQ summary script
		cat("Reading output from CAP-miRSEQ summary script...\n")
		counts <- read.table(expr.file, sep="\t", header=T, stringsAsFactor=F)
		# assign unique mature_precursor id to each row
		row.names(counts) <- expression.raw$Mature.miRNA
		# extract samples used in this comparison
		samples <- make.names(samp.info$SampleNames)
		counts <- counts[, samples]
	}
	# in case of untypical gene identifiers change those
	## for "gene:" in front of the Ensembl Gene ID
	rownames(counts) <- sub("^gene:", "", rownames(counts))
	return(counts)
}

#' Function to filter counts
#' @export
diff_expr_filter_counts <-
		function(counts, samp.info, strict=TRUE, min.samp=NULL)
{
	#### Important: CPMs must be calculated with all counts including the non-aligned ones so as not to distort the results
	#### because: CPM <- apply(countmatrix, 2, function(x) (x/sum(x))*1000000) # uses sum of ALL counts in that sample
	noint_names <- grep("no_feature|ambiguous|too_low_aQual|not_aligned|alignment_not_unique", rownames(counts), value=TRUE)
	noint <- rownames(counts) %in% noint_names
	## In edgeR, it is recommended to remove features without at least 1 read per million in n of the
	## samples, where n is the size of the smallest group of replicates (determined from the 'groups' vector)
	### can be overridden by 'min.samp'
	### if we want to be really strict we only keep a miRNA if there are > 5 reads per million in at least half of the samples
	cpms <- cpm(counts)
	if (strict) {
		cat("  Using 'strict' filtering...\n")
		keep <- rowSums(cpms > 5) >= ceiling(ncol(counts)/2) & !noint
	} else {
		if(is.null(min.samp)) {
			min.samp <- min(table(samp.info$Groups))
		}
		keep <- rowSums(cpms > 1) >= min.samp & !noint
	}
	cat("  Removing", length(which(!keep)), "and keeping", length(which(keep)), "rows...\n")
	counts <- counts[keep, ]
	## Visualize and inspect the count table
	colnames(counts) <- basename(colnames(counts))
	return(counts)
}

#' Function to create design matrix
#' @export
diff_expr_make_design <-
		function(samp.info, groups, pairs=NULL, block=FALSE)
{
	if (block || is.null(pairs)) {
		cat("Creating simple design matrix...\n")
		design <- model.matrix(~0+groups)
		colnames(design) <- gsub("groups", "", colnames(design))
	} else if (!is.null(pairs)) {
		cat("Creating design matrix for paired samples. Using column", sQuote(pairs), "as 'pairs' variable...\n")
		pairs <- samp.info[[pairs]]
		if (!is.numeric(pairs)) {
			pairs <- dropEmptyLevels(as.factor(samp.info[[pairs]]))
			cat(" ", levels(pairs), "\n")
			design <- model.matrix(~pairs+groups)
		} else {
			design <- model.matrix(~groups+pairs)
		}
	}
	return(design)
}

#' Function to make contrast matrix
#' @export
diff_expr_make_contrasts <-
		function(design, pairs=NULL, block=FALSE, contrasts=NULL)
{
	if (is.null(contrasts)) {
		cat("Comparing all groups vs. all...\n")
		if (block || is.null(pairs)) {
			cat("  Using all levels...\n")
			n <- colnames(design)
		} else if (!is.null(pairs)) {
			cat("  Extracting 'groups' levels...\n")
			n <- grep("^groups.+", colnames(design), value=TRUE)
		}
		if (length(n)==1L || length(grep("__", n))) {
			cat("  ! Skipping contrast matrix creation !\n")
			return(NULL)
		}
		contrasts <- unlist(lapply(n[1:(length(n)-1)], function(x) {
							contr <- paste(n[n!=x], x, sep="-")
							cyc <- which(n==x)
							contr[cyc:length(contr)]
						}))
		cat("  ", contrasts, "\n")
	} else {
		cat("  Comparing selected groups", contrasts, "\n")
	}
	cat("  Creating contrast matrix...\n")
	contrasts <- suppressWarnings(makeContrasts(contrasts=contrasts, levels=design))
	return(contrasts)
}

#' Function to compute linear model fit and optionally apply 'voom' beforehand
#' @export
diff_expr_fit <-
		function(counts, d, design, do.voom=TRUE, voom.fun=voom, norm.method=c("quantile", "tmm"), bayes.trend=FALSE, bayes.robust=FALSE, pairs=NULL,
				pairs_col=NULL, block=FALSE, contrasts=NULL, disp="tagwise.dispersion")
{
	if (do.voom) {
		if (norm.method=="tmm") {
			cts <- d
			norm.method="none"
		} else {
			cts <- counts
		}
		v <- voom.fun(cts, design=design, plot=FALSE, normalize.method=norm.method)

		# For paired samples or block designs:
		if (block && !is.null(pairs)) {
			if (!is.factor(pairs)) {
				stop("For block designs 'pairs' needs to be a factor.")
			}
			cat("  Samples are paired. Using column", sQuote(pairs_col), "as block variable...\n")
			cat("    ", levels(pairs), "\n")
			cat("  Calculating consensus correlation...\n")
			corfit <- duplicateCorrelation(v$E , design, block=pairs)
			cat("  Fitting linear model using consensus correlation...\n")
			fit <- lmFit(v, design, block=pairs, correlation=corfit$consensus)
		} else {
			cat("  Fitting linear model...\n")
			fit <- lmFit(v, design)
		}
		if (!is.null(contrasts)) {
			if (length(grep("^Intercept$", rownames(contrasts)))) {
				rownames(contrasts)[grep("^Intercept$", rownames(contrasts))] <- "(Intercept)"
			}
			cat("  Fitting contrasts...\n")
			fit2 <- contrasts.fit(fit, contrasts)
			cat("  eBayes fit...\n")
			fit2 <- eBayes(fit2, trend = bayes.trend, robust = bayes.robust)
		} else {
			cat("  eBayes fit...\n")
			fit2 <- eBayes(fit, trend = bayes.trend, robust = bayes.robust)
		}
		return(list(v=v, fit=fit, fit2=fit2))
	} else {
		## Estimate dispersion values, relative to the design matrix, using the Cox-Reid (CR)-adjusted likelihood
		cat("  Estimating dispersion values...\n")
		d2 <- estimateGLMTrendedDisp(d, design)
		d2 <- estimateGLMTagwiseDisp(d2, design)
		# Given the design matrix and dispersion estimates, fit a GLM to each feature
		cat("  Fitting linear model...\n")
		fit <- glmFit(d2, design, dispersion=d2[[disp]])
		return(list(d=d, d2=d2, fit=fit))
	}
}

#' Function to extract contrasts and generate top tables and plots
#' @export
diff_expr_extract_contrasts <-
		function(contrasts=NULL, fit, fit2=NULL, normcnt, out.l, do.voom=TRUE, out.dir=NULL,
				analysis.name=NULL, biomart=FALSE, biom.data.set="hsapiens_gene_ensembl", biom.mart=c("ensembl", "snp", "funcgen", "vega", "pride", "plants"),
				host="www.ensembl.org", biom.filter="ensembl_gene_id", biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"), sym.col="hgnc_symbol",
				rm.dups=FALSE, p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, point.lab=TRUE, font.size=5, plots=TRUE, lists=TRUE)
{
	if (!length(grep("contrasts", names(out.l)))) {
		out.l$contrasts <- list()
	}
	if (is.null(contrasts)) {
		cat("  Extracting 'groups' levels from design...\n")
		cn <- grep("^groups.+", colnames(fit$design), value=TRUE)
	} else if (is.matrix(contrasts) && !is.null(colnames(contrasts))) {
		# if do.voom=TRUE contrasts have been calculated already in the fit function and only need to be extracted
		# in the case of paired samples, contrasts are inherent to the design and only need to be extracted
		# otherwise, we need to feed the contrast matrix to glmLRT to instruct it to calculate the desired contrasts
		# see the different behaviour of glmLRT below for do.voom=FALSE
		cn <- colnames(contrasts)
	} else {
		# contrasts is a character vector
		# this will only be called for the non-contrasted columns of the design matrix for paired samples
		# which means contrasts are inherent to the design and only need to be extracted
		cn <- contrasts
	}
	for (contr in cn) {
		cat("Calculating differential expression for", contr, "\n")
		if (do.voom) {
			cat("Generating output table of differentially expressed features...\n")
			tt <- topTable(fit2, coef=contr, number=nrow(fit2), sort.by="P")
		} else {
			# Perform a likelihood ratio test, specifying the contrast of interest.
			# Needs to be done per-contrast as otherwise it will perform the LR test of all contrasts together while we want this done individually.
			cat("Performing likelihood ratio test on this contrast...\n")
			if (is.matrix(contrasts)) {
				# calculating the contrast
				de <- glmLRT(fit, contrast = contrasts[, contr])
			} else {
				# only extracting the contrast (for paired samples)
				de <- glmLRT(fit, coef=contr)
			}
			# Use the topTags function to present a tabular summary of the differential expression statistics (note that topTags
			# operates on the output of exactTest or glmLRT, but only the latter is shown here)
			cat("Generating tablular summary of differential expression statistics ('top table')\n")
			tt <- topTags(de, n = nrow(de))
#			} else {
#				stop("Need contrast matrix as input.")
#			}
		}
		if (is.null(contrasts)) {
			fitcnt <- fit$coefficients[, contr]
			addinfo <- cbind(normcnt, fitcnt)
			if (do.voom) {
				names(addinfo)[names(addinfo) %in% "fitcnt"] <- "Fitted Coefficients (log2)"
			} else {
				names(addinfo)[names(addinfo) %in% "fitcnt"] <- "Fitted Coefficients (ln)"
			}
		} else if (is.matrix(contrasts)) {
			fitcnt <- fit$coefficients[, rownames(contrasts)[contrasts[, contr]!=0]]
			addinfo <- cbind(normcnt, fitcnt)
		} else {
			addinfo <- normcnt
		}
		d3 <- merge(addinfo, tt, by="row.names", sort=FALSE)
		cat("Renaming ID column...\n")
		names(d3)[1] <- "ID"
		if (biomart) {
			d3 <- diff_expr_biomart(d3, biom.data.set, biom.mart, host, biom.filter, biom.attributes, sym.col, rm.dups)
			id.col <- names(d3)[names(d3) %in% biom.filter]
		} else {
			syms <- convertId2(as.character(d3$ID))
			syms <- data.frame(ID=names(syms), gene_symbol=as.character(syms), stringsAsFactors=FALSE)
			d3 <- merge(syms, d3, by="ID", all.y=TRUE, all.x=FALSE, sort=TRUE)
			if (any(d3$gene_symbol=="") || any(is.na(d3$gene_symbol))) {
				cat("  Replacing", length(which(d3$gene_symbol=="" | is.na(d3$gene_symbol))), "missing Gene Symbols by Ensembl IDs...\n")
				d3$gene_symbol[d3$gene_symbol=="" | is.na(d3$gene_symbol)] <- as.character(d3$ID[d3$gene_symbol=="" | is.na(d3$gene_symbol)])
			}
			id.col <- "ID"
		}
		cat("Setting unique row names...\n")
		rownames(d3) <- make.unique(as.character(d3[[id.col]]))
		out.l$contrasts[[contr]] <- d3
		if (lists) {
			DE.out <- paste(analysis.name, contr, "differential_expression.tsv", sep="_")
			cat("Saving list to", DE.out, "...\n")
			write.table(d3, file.path(out.dir, DE.out), sep="\t", quote=FALSE, row.names=FALSE)
		}

		# Create a graphical summary, such as an M (log-fold change) versus A (log-average expression) plot, here showing the
		# genes selected as differentially expressed (with a 5% false discovery rate)
		if (plots) {
			cat("Plotting...\n")
			pdf(file.path(out.dir, paste(analysis.name, contr, "_plots.pdf", sep="_")), width=11, height=8.5)
			par(mar = c(6,6,5,3))
			out.l$maplots <- list()
			cat(" MA-plot...\n")
			out.l$MAplots[[contr]] <- diff_expr_ma_plot(d3, contr, p.thr, fdr.thr, logfc.thr, numlab, out.dir, analysis.name, point.lab, biom.attributes, font.size, lists)

			## Volcano plot
			out.l$volcanoPlots <- list()
			cat(" Volcano plot...\n")
			out.l$volcanoPlots[[contr]] <- diff_expr_volcano_plot(d3, id.col, sym.col="gene_symbol", p.thr=p.thr, fdr.thr=fdr.thr, logfc.thr=logfc.thr, numlab=numlab, point.lab=point.lab)

#png(paste(out.dir,"/",analysis.name,".Pvalue_distribution.png",sep=""),width=1280,height=960,res=150)
			## Histogram of P-value distribution
			cat(" Dendrogram plot...\n")
			diff_expr_pval_hist_plot(d3)
			dev.off()

			cat("done\n")
		}
	}
	return(out.l)
}

#' Function to calculate pseudo counts representing batch-corrected normalised but untransformed values
#' @export
diff_expr_pseudo_counts <-
		function(design, d, pairs, disp="tagwise.dispersion", do.cpm=TRUE)
{
	cat("    Estimating dispersion...")
	disp.mat <- estimateDisp(d, design)
	cat("done\n    Fitting generalised linear model...")
	fit0 <- glmFit(d, design, dispersion=disp.mat[[disp]])
	old.fitted <- fit0$fitted.values
	batch.coefs <- grep(pairs, colnames(design))
	new.coefs <- fit0$unshrunk.coefficients
	cat("done\n    Set coefficients for blocking variable to 0...")
	new.coefs[, batch.coefs] <- 0
	cat("done\n    Refit coefficients...")
	new.fitted <- exp(new.coefs %*% t(design) + as.vector(fit0$offset))
	cat("done\n    Getting pseudo-counts...")
	pseudo.counts <- q2qnbinom(d$counts, old.fitted, new.fitted, dispersion=disp.mat[[disp]])
	cat("done\n")
	if (do.cpm) {
		cat("    Getting CPMs...")
		pseudo.counts <- cpm(pseudo.counts, log=TRUE, prior.count=3)
		cat("done\n")
	}
	return(pseudo.counts)
}

#' Function to retrieve additional information from biomart
#' @export
diff_expr_biomart <-
		function(d3, biom.data.set="hsapiens_gene_ensembl", biom.mart=c("ensembl", "snp", "funcgen", "vega", "pride", "plants"),
				host="www.ensembl.org", biom.filter="ensembl_gene_id", biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"),
				sym.col="hgnc_symbol", rm.dups=FALSE)
{
	gene.lab <- convert.bm(d3, "ID", biom.data.set, biom.mart, host, biom.filter, biom.attributes, sym.col, rm.dups)
	names(gene.lab)[names(gene.lab)==sym.col] <- "gene_symbol"
	cat("  Extended annotation:\n")
	biom.attributes[biom.attributes==sym.col] <- "gene_symbol"
	if (length(d3$ID)>8) {
		print(gene.lab[1:8, biom.attributes])
		cat("_truncated_ (", length(d3$ID), "features)\n")
	} else {
		print(gene.lab[, biom.attributes])
	}
	return(gene.lab)
}

#' Function to do PCA using `stats::prcomp`
#' @export
diff_expr_PCA <-
		function(counts, n=500, scale.=FALSE)
{
	select <- 1:nrow(counts)
	if (!is.null(n)) {
		cat("    Getting row-wise variances...")
		Pvars <- genefilter::rowVars(counts)
		cat("done\n    Selecting", n, "rows with highest variances...")
		select <- order(Pvars, decreasing = TRUE)[seq_len(min(n, length(Pvars)))]
		cat("done\n")
	}
	cat("    Calculating principal components...")
	PCA <- prcomp(t(counts[select, ]), scale.=scale.)
	cat("done\n")
	return(PCA)
}

#' Function to generate a MDS plot usig `ggplot2`
#' @export
diff_expr_ggplot_mds <-
		function(counts, samp.name, groups, grp.nam=NULL, pairs=NULL, pairs.name=NULL, gene.selection="common", dim.plot=c(1,2), main=NULL)
{
	cat("    Preparing data...")
	mds <- plotMDS(counts, gene.selection=gene.selection, dim.plot=dim.plot, plot=FALSE)
	dat <- data.frame(SampleName=samp.name, Groups=groups, x=mds$x, y=mds$y)
	cat("done\n    Plotting...")
	g <- ggplot(dat, aes(x, y, colour=Groups))
	if (!is.null(pairs)) {
		dat <- data.frame(SampleName=samp.name, Groups=groups, Block=pairs, x=mds$x, y=mds$y)
		if (is.factor(dat$Block) && length(levels(dat$Block)) <= 6) {
			cat("\n     Block design using a discrete variable. Shaping points by blocking variable...\n")
			g <- ggplot(dat, aes(x, y, colour=Groups, shape=Block))
			if (!is.null(pairs.name)) {
				g <- g + scale_shape_discrete(name=pairs.name)
			}
		} else if (is.numeric(dat$Block)) {
			cat("\n     Block design using a continuous variable. Sizing points by blocking variable...\n")
			g <- ggplot(dat, aes(x, y, colour=Groups, size=Block))
			if (!is.null(pairs.name)) {
				g <- g + scale_size_continuous(name=pairs.name)
			}
		}
	}
	g <- g + geom_point()
	g <- g + geom_text_repel(
			data = dat,
			aes(label = SampleName),
			size = 5,
			box.padding = unit(0.35, "lines"),
			point.padding = unit(0.3, "lines"),
			show.legend = FALSE)
	if (!is.null(grp.nam)) {
		g <- g + scale_color_discrete(name=grp.nam)
	}
	g <- g + ggtitle(paste0("Multi-dimensional scaling (", main, ")"))
	print(g)
	cat("    done\n")
	return(g)
}

## PCA plots
#' Function to generate a PCA biplot using `medseqr::ggbiplot`
#' @export
diff_expr_PCA_ggbiplot <-
		function(PCA, groups, grp.nam=NULL, ellipse=TRUE, circle=TRUE, varname.size=0, var.axes=FALSE, main=NULL, fix.aspect=FALSE, tweak=FALSE, ...)
{
	main <- paste("Biplot for PCA (", main, ")")
	cat("    Plotting...")
	g <- medseqr::ggbiplot.n(PCA, var.scale = 1, obs.scale = 1, groups = groups, grp.nam=grp.nam, ellipse = ellipse, circle = circle, varname.size = varname.size, var.axes = var.axes, main=main, fix.aspect=fix.aspect, tweak=tweak, ...)
	print(g)
	cat("done\n")
	return(g)
}

#' Function to generate an ordinary two-dimensional PCA plot using `ggplot2`
#' @export
diff_expr_PCA_ggplot <-
		function(PCA, samp.name=NULL, groups, grp.nam=NULL, PC=c(1,2), main=NULL)
{
	cat("    Preparing data...")
	if (is.null(samp.name)) {
		samp.n <- rownames(PCA$x)
	} else if (is.na(samp.name)) {
		samp.n <- ""
	} else {
		stop("samp.name can only be 'NULL' to use the row names of the principal components matrix or 'NA' to be empty.")
	}

	percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2), 1)
	dataGG <- data.frame(PCx=PCA$x[, PC[1]], PCy=PCA$x[, PC[2]], Condition=groups, Sample=samp.n)
	if (is.null(grp.nam)) {
		grp.nam <- "Condition"
	}
	cat("done\n    Plotting...")
	g <- ggplot(data=dataGG, aes(PCx, PCy, color=Condition))
	g <- g + geom_point()
	g <- g + ggtitle(paste0("PCA (", main, ")"))
	g <- g + labs(x=paste0("PC", PC[1], ", VarExp:", round(percentVar[PC[1]], 4)),
			y=paste0("PC", PC[2], ", VarExp:", round(percentVar[PC[2]], 4)))
	g <- g + scale_colour_brewer(name=grp.nam, type="qual", palette=2)
	if (is.null(samp.name)) {
		g <- g + geom_text_repel(aes(label=Sample),
				data=dataGG,
				size = 5,
				box.padding = unit(0.35, "lines"),
				point.padding = unit(0.3, "lines"),
				show.legend = F)
	}
	print(g)
	cat("done\n")
	return(g)
}

#' Function to generate a 3D scatterplot
#' @export
diff_expr_3d_scatterplot <-
		function(PCA, samp.name=NULL, groups, grp.nam=NULL, PC=c(1,2,3), main=NULL)
{
	cat("    Preparing data...")
	if (is.null(samp.name)) {
		samp.name <- rownames(PCA$x)
	} else if (is.na(samp.name)) {
		samp.name <- ""
	} else {
		stop("samp.name can only be 'NULL' to use the row names of the principal components matrix or 'NA' to be empty.")
	}

	percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2), 1)
	dat <- data.frame(PCx=PCA$x[, PC[1]], PCy=PCA$x[, PC[2]], PCz=PCA$x[, PC[3]], Condition=groups)
	cond <- levels(dat$Condition)
	col_seq <- rev(rep(c(seq.int(from=2, to=12, by=2), seq.int(from=1, to=11, by=2)), ceiling(length(cond)/12))[1:length(cond)])
	cols <- brewer.pal(n=12, name="Paired")[col_seq]
	plcol <- rep(cols[1], nrow(dat))
	names(plcol) <- dat$Condition
	if (is.null(grp.nam)) {
		grp.nam <- "Condition"
	}
	for (i in 2:length(cond)) {
		plcol[dat$Condition == cond[i]] <- cols[i]
	}
	cat("done\n    Plotting...\n     scatterplot...\n")
	s3d <- scatterplot3d(dat[,1:3],        # x y and z axis
			color=plcol, pch=19,        # circle color indicates no. of cylinders
			type="h", lty.hplot=2,       # lines to the horizontal plane
			scale.y=.75,                 # scale y axis (reduce by 25%)
			main=paste0("3-D Scatterplot for PCA (", main, ")"))
	cat("     point labels...\n")
	s3d.coords <- s3d$xyz.convert(dat[,1:3])
	text(s3d.coords$x, s3d.coords$y,     # x and y coordinates
			labels=samp.name,       # text to plot
			pos=4, cex=.5)                  # shrink text 50% and place to right of points)
# add the legend
	cat("     legend...\n")
	legend("topleft", inset=.05,      # location and inset
			bty="n", cex=.5,              # suppress legend box, shrink text 50%
			title=grp.nam,
			legend=unique(names(plcol)), fill=unique(plcol))
	cat("    done\n")
}

#' Function to generate dendrogram plots based on hierarchical clustering
#' @export
diff_expr_dendro_plot <-
		function(counts, groups, grp.nam=NULL, main=NULL)
{
	cat("    Hierarchical clustering...")
	hc <- hclust(dist(t(counts)))
	plot(hc, main=paste("Hierarchical Clustering (", main, ")"))
	cat("done\n    Generating coloured dendrogram...")
	dend <- as.dendrogram(hc)
	labels_colors(dend) <- as.numeric(groups)[hc$order]
	par(mar=c(8,6,6,4))
	plot(dend, main=paste0("Hierarchical Clustering (", main, ")\n[coloured by ", grp.nam, "]"))
	cat("done\n")
}

#' Main wrapper function for QC plots
#' @export
diff_expr_QC_plots <-
		function(counts, samp.info, control, out.l, grp.nam=NULL, PC=c(1,2,3), ellipse=TRUE, circle=TRUE, varname.size=0, var.axes=FALSE, samp.lab=TRUE, pairs=NULL,
				pairs.name=NULL, gene.selection="common", n=500, type=NULL, analysis.name=NULL, out.dir=NULL)
{
	cat("  Doing PCA...\n")
	PCA <- diff_expr_PCA(counts=counts, n=n)
	cat("  done\n")
	groups <- relevel(samp.info$Groups, ref=control)
	samp.name <- samp.info$SampleNames
	samp.name_pca <- NA
	if (samp.lab) {
		samp.name_pca <- NULL
	}
	main <- paste(type, analysis.name, sep="_")
	main <- gsub("\\.{1,}", "_", make.names(main))
	out.l$QCplots <- list()
	cat("  Plotting...\n")
	pdf_file <- file.path(out.dir, paste0(Sys.Date(), "_", main, "_QC_plots.pdf"))
	cat("   Saving plot to", pdf_file, "...\n")
	pdf(pdf_file, width=11, height=11)
	main <- paste(type, analysis.name)
	cat("   MDS ggplot...\n")
	out.l$QCplots[["MDS"]] <- diff_expr_ggplot_mds(counts=counts, samp.name=samp.name, groups=groups, grp.nam=grp.nam, pairs=pairs, pairs.name=pairs.name, gene.selection=gene.selection, dim.plot=PC[1:2], main=main)
	cat("   done.\n   PCA ggbiplot...\n")
	out.l$QCplots[["PCAbiplot"]] <- diff_expr_PCA_ggbiplot(PCA=PCA, groups=groups, grp.nam=grp.nam, ellipse=ellipse, circle=circle, varname.size=varname.size, var.axes=var.axes, main=main)
	cat("   done.\n   PCA ggplot...\n")
	out.l$QCplots[["PCAlabelledPlot"]] <- diff_expr_PCA_ggplot(PCA=PCA, samp.name=samp.name_pca, groups=groups, grp.nam=grp.nam, PC=c(1,2), main=main)
	cat("   done.\n   PCA 3d scatterplot...\n")
	diff_expr_3d_scatterplot(PCA=PCA, samp.name=samp.name_pca, groups=groups, grp.nam=grp.nam, PC=PC[1:3], main=main)
	cat("   done.\n   PCA cluster dendrogram...\n")
	diff_expr_dendro_plot(counts=counts, groups=groups, grp.nam=grp.nam, main=main)
	cat("   done.\n")
	dev.off()
	cat("  Plotting finished.\n")
	return(out.l)
}

#' Function to generate a MDS plot using `limma::plotMDS`
#' @export
diff_expr_mds_plot <-
		function(d, groups, n=500, sample.plot.names=NULL, analysis.name=NULL, do.pdf=FALSE, out.dir=NULL)
{
	if (!is.null(samples)) {
		cat("  *** Using custom sample labels: ***\n  ", head(sample.plot.names), "\n")
	}
	if (do.pdf) {
		pdf(file.path(out.dir, paste0(analysis.name, "_MDS_plot.pdf")), width=11, height=11)
	}
	par(mar = c(6,6,5,3))
	plotMDS(d, top=n, labels=sample.plot.names, main=paste0("MDS plot for '", analysis.name, "' normalised DGEList"), col = rainbow(length(levels(groups)))[factor(groups)])
	legend("bottomright", legend=levels(groups), pch=15, col=rainbow(length(levels(groups))))
	if (do.pdf) {
		dev.off()
	}
}

#' Function to generate a M-A plot using `ggplot2`
#' @export
diff_expr_ma_plot <-
		function(dat, contr, p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, out.dir=NULL, analysis.name=NULL, point.lab=TRUE, biom.attributes=c("ensembl_gene_id","hgnc_symbol","description"),
				font.size=5, lists=TRUE)
{
	rn <- rownames(dat)
	pv.col <- names(dat)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(dat)))]
	fdr.col <- names(dat)[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(dat)))]
	numlab <- ceiling(1.25*numlab)
	A <- grep("^logCPM$|^AveExpr$", names(dat), value=TRUE)
	degFDR <- rn[dat[[fdr.col]] < fdr.thr & abs(dat$logFC) >= logfc.thr]
	degPval <- rn[dat[[pv.col]] < p.thr & abs(dat$logFC) >= logfc.thr]
	dat$`P-Value` <- dat[[pv.col]]
	dat$`adj. P-Value` <- dat[[fdr.col]]
	dat$`log2 Fold-Change` <- abs(dat$logFC)
	dat$`Average Expression` <- dat[[A]]
	# list to collect ggplot2 objects for output
	g.l <- list()
	cat("  M-A plot...\n")
	## BiomaRt
#				marts <- listMarts(host=host)[["biomart"]]
#				marts1 <- unlist(lapply(strsplit(tolower(marts), "_"), function(x) x[length(x)]))
#				biom <- match.arg(biom.mart)
#				biom <- marts[grep(biom, marts1)]
#				cat("Using BioMart:", biom, "\n")
#				mart <- useDataset(dataset=biom.data.set, useMart(biomart=biom, host=host))
#				cat("   Getting more information:", biom.attributes[biom.attributes!=biom.filter], "...\n")
	if (length(degFDR)>0) {
		cat(" FDR filtered values...\n")
#					biom.ids <- getBM(attributes=biom.attributes, filters=biom.filter, values=degFDR, mart=mart)

#					gene.lab <- tt$table[rn %in% degFDR, ]
#					gene.lab <- merge(biom.ids, gene.lab, by.x=biom.filter, by.y="row.names", all.x=FALSE)

		## ggplot2 M-A plot
		g <- ggplot(data=dat, aes(x=`Average Expression`, y=logFC))
		g <- g + geom_point(aes(size=`log2 Fold-Change`, color=`adj. P-Value`, alpha=`log2 Fold-Change`))
		g <- g + scale_colour_gradient2(low="#00106B", high="#A4B1FF", mid="#F3F5FF", midpoint=0.2)
		if (point.lab) {
			gene.lab <- dat[rn %in% degFDR, ]
			cat("    ", nrow(gene.lab), "point(s) labelled...\n")
			if (nrow(gene.lab)>numlab) {
				cat("     Restricting to", numlab, "...\n")
				ix <- sort(gene.lab$`adj. P-Value`, index=T)$ix
				gene.lab <- gene.lab[ix[1:numlab], ][order(ix[1:numlab]), ]
			}
			cat("   Highlighted features:\n")
			if (length(degFDR)>8) {
				print(gene.lab[1:8, 1:2])
				cat("_truncated_ (", length(degFDR), "features)\n")
			} else {
				print(gene.lab[1:8, 1:2])
			}
			g <- g + ggtitle(paste0("M-A plot for ", contr, " (highl.: FDR < ", fdr.thr, "; FC >= ", 2^logfc.thr, "-fold)"))
			g <- g + geom_text_repel(data = gene.lab, aes(label = gene_symbol), size = font.size, box.padding = unit(0.35, "lines"), point.padding = unit(0.3, "lines"), show.legend = F)
			if (lists) {
				write.table(gene.lab, file.path(out.dir, paste(analysis.name, contr, "labelledPointsSmearPlot.tsv", sep="_")), sep="\t", quote=FALSE, row.names=FALSE)
			}
		} else {
			g <- g + ggtitle(paste("M-A plot for", contr))
		}
		print(g)
		g.l[["FDR"]] <- g
	}
	if (length(degPval)>0) {
		cat("    for P-value filtered values...\n")
#					biom.ids <- getBM(attributes=biom.attributes, filters=biom.filter, values=degPval, mart=mart)

#					gene.lab <- tt$table[rn %in% degPval, ]
#					gene.lab <- merge(biom.ids, gene.lab, by.x=biom.filter, by.y="row.names", all.x=FALSE)

		## ggplot implemetation of MA plot
		g <- ggplot(data=dat, aes(x=`Average Expression`, y=logFC))
		g <- g + geom_point(aes(size=`log2 Fold-Change`, color=`P-Value`, alpha=`log2 Fold-Change`))
		g <- g + scale_colour_gradient2(low="#00106B", high="#A4B1FF", mid="#F3F5FF", midpoint=0.2)
		if (point.lab) {
			gene.lab <- dat[rn %in% degPval, ]
			cat("    ", nrow(gene.lab), "point(s) labelled...\n")
			if (nrow(gene.lab)>numlab) {
				cat("     Restricting to", numlab, "...\n")
				ix <- sort(gene.lab$`P-Value`, index=T)$ix
				gene.lab <- gene.lab[ix[1:numlab], ][order(ix[1:numlab]), ]
			}
			cat("   Highlighted features:\n")
			if (length(degPval)>8) {
				print(gene.lab[1:8, 1:2])
				cat(paste0("   _truncated_ (", length(degPval), " features)\n"))
			} else {
				print(gene.lab[1:8, 1:2])
			}
			g <- g + ggtitle(paste0("M-A plot for ", contr, " (highl.: P-value < ", p.thr, "; FC >= ", 2^logfc.thr, "-fold)"))
			g <- g + geom_text_repel(data = gene.lab, aes(label = gene_symbol), size = font.size, box.padding = unit(0.35, "lines"), point.padding = unit(0.3, "lines"), show.legend = F)
			if (lists) {
				write.table(gene.lab, file.path(out.dir, paste(analysis.name, contr, "labelledPointsSmearPlot.tsv", sep="_")), sep="\t", quote=FALSE, row.names=FALSE)
			}
		} else {
			g <- g + ggtitle(paste("M-A plot for", contr))
		}
		print(g)
		g.l[["Pval"]] <- g
	}
	return(g.l)
}

#' Function to generate a Volcano plot using `ggplot2`
#' @export
diff_expr_volcano_plot <-
		function(d3, id, sym.col="gene_symbol", p.thr=0.05, fdr.thr=0.05, logfc.thr=1, numlab=15, point.lab=TRUE)
{
	pv.col <- names(d3)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
	fdr.col <- names(d3)[grep("^fdr$|^adj*\\.{0,1}p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
	g.l <- list()
	cat("  Volcano plot of FDR values...\n")
	## Updated: using ggplot2
	if (point.lab) {
		cont.dat.fdr <- d3[, c(id, sym.col, "logFC", pv.col, fdr.col)]
		if (any(cont.dat.fdr$gene_symbol=="" || any(is.na(cont.dat.fdr$gene_symbol)))) {
			repl <- which(cont.dat.fdr$gene_symbol==""|is.na(cont.dat.fdr$gene_symbol))
			cont.dat.fdr[repl, sym.col] <- cont.dat.fdr[repl, as.character(id)]
		}
	} else {
		cont.dat.fdr <- d3[, c(id, "logFC", pv.col, fdr.col)]
	}
	cont.dat.fdr$fdr <- cont.dat.fdr[[fdr.col]]
	cont.dat.fdr$`FDR-Values` <- "not signif."
	cont.dat.fdr$`FDR-Values`[cont.dat.fdr$fdr<fdr.thr] <- paste0("signif. (FDR<", fdr.thr, ")")
	cont.dat.fdr$FC <- paste0("less than ", 2^logfc.thr, "-fold")
	cont.dat.fdr$FC[(cont.dat.fdr$logFC < -1*logfc.thr | cont.dat.fdr$logFC > logfc.thr)] <- paste0("more than ", 2^logfc.thr, "-fold")
	filtdat <- cont.dat.fdr[cont.dat.fdr$fdr < fdr.thr, ]
	cat("    ", nrow(filtdat), "point(s) labelled...\n")
	if (nrow(filtdat)>numlab) {
		cat("     Restricting to", numlab, "...\n")
		ix <- sort(filtdat$fdr, index=T)$ix
		filtdat <- filtdat[ix[1:numlab], ][order(ix[1:numlab]), ]
	}
	gfdr <- ggplot(cont.dat.fdr, aes(x=logFC, y=-log10(fdr), color=`FDR-Values`, fill=`FDR-Values`, size=FC))
	gfdr <- gfdr + geom_point(alpha=0.4)
	gfdr <- gfdr + scale_color_manual(values=c("#0066FF", "#CC0000"))
	gfdr <- gfdr + geom_hline(aes(yintercept=-log10(0.05)), colour="red", linetype="dashed")
	gfdr <- gfdr + geom_vline(aes(xintercept=1), colour="red", linetype="dashed")
	gfdr <- gfdr + geom_vline(aes(xintercept=-1), colour="red", linetype="dashed")
	gfdr <- gfdr + theme_bw(base_size = 10)
	gfdr <- gfdr + geom_text(data=cont.dat.fdr, aes(x=floor(min(logFC)), y=-log10(0.05)), label="q=0.05", nudge_x=-1.5, nudge_y=max(-log10(cont.dat.fdr$fdr))/60, size=3, color="red")
	gfdr <- gfdr + geom_text(x=0, y=-0.7, label="two-fold FC", size=3, color="red")
	if (point.lab) {
		gfdr <- gfdr + geom_text_repel(
				data = filtdat,
				aes(label = filtdat[[sym.col]]),
				size = 5,
				box.padding = unit(0.35, "lines"),
				point.padding = unit(0.3, "lines"),
				show.legend = F
		)
	}
	print(gfdr)
	g.l[["FDR"]] <- gfdr
#			plot(d3$logFC, -log10(d3$FDR), col=ifelse(d3$FDR<0.05, "red", "black"), main="FDR volcano plot", xlab="log2FC", ylab="-log10(FDR)")
#dev.off()

#png(paste(out.dir,"/",analysis.name,".Pvalue.volcano_plot.png",sep=""),width=1280,height=960,res=150)
	## Volcano plot of P-values
	cat("  Volcano plot of P -values...\n")
	## Updated: using ggplot2
	if (point.lab) {
		cont.dat <- d3[, c(id, sym.col, "logFC", pv.col, fdr.col)]
		if (any(cont.dat$gene_symbol=="")) {
			cont.dat[cont.dat$gene_symbol=="", sym.col] <- cont.dat[cont.dat$gene_symbol=="", id]
		}
	} else {
		cont.dat <- d3[, c(id, "logFC", pv.col, fdr.col)]
	}
	cont.dat$pval <- cont.dat[[pv.col]]
	cont.dat$`P-Values` <- "not signif."
	cont.dat$`P-Values`[cont.dat$pval<p.thr] <- paste0("signif. (P<", p.thr, ")")
	cont.dat$FC <- paste0("less than ", 2^logfc.thr, "-fold")
	cont.dat$FC[(cont.dat$logFC < -1*logfc.thr | cont.dat$logFC > logfc.thr)] <- paste0("more than ", 2^logfc.thr, "-fold")
	filtdat <- cont.dat[cont.dat$pval < p.thr, ]
	cat("    ", nrow(filtdat), "point(s) labelled...\n")
	if (nrow(filtdat)>numlab) {
		cat("     Restricting to", numlab, "...\n")
		ix <- sort(filtdat$pval, index=T)$ix
		filtdat <- filtdat[ix[1:numlab], ][order(ix[1:numlab]), ]
	}
	g <- ggplot(cont.dat, aes(x=logFC, y=-log10(pval), color=`P-Values`, fill=`P-Values`, size=FC))
	g <- g + geom_point(alpha=0.4)
	g <- g + scale_color_manual(values=c("#0066FF", "#CC0000"))
	g <- g + geom_hline(aes(yintercept=-log10(0.05)), colour="red", linetype="dashed")
	g <- g + geom_vline(aes(xintercept=1), colour="red", linetype="dashed")
	g <- g + geom_vline(aes(xintercept=-1), colour="red", linetype="dashed")
	g <- g + theme_bw(base_size = 10)
	g <- g + geom_text(data=cont.dat, aes(x=floor(min(logFC)), y=-log10(0.05)), label="p=0.05", nudge_x=-1.5, nudge_y=max(-log10(cont.dat$pval))/60, size=3, color="red")
	g <- g + geom_text(x=0, y=-0.7, label="two-fold FC", size=3, color="red")
	if (point.lab) {
		g <- g + geom_text_repel(
				data = filtdat,
				aes(label = filtdat[[sym.col]]),
				size = 5,
				box.padding = unit(0.35, "lines"),
				point.padding = unit(0.3, "lines"),
				show.legend = F
		)
	}
#			pdf(file.path(home, "differential_expression/chemosensitive_vs_chemoresistant_volcano.pdf"), width=12, height=12)
	print(g)
	g.l[["Pval"]] <- g
	return(g.l)
#			dev.off()
#			plot(d3$logFC, -log10(d3$PValue), col=ifelse(d3$PValue<0.01,"red","black"), main="P-value volcano plot", xlab="log2FC", ylab="-log10(Pvalue)")
#dev.off()
}

#' Function to generate a histogram of the P-Value distribution
#' @export
diff_expr_pval_hist_plot <-
		function(d3)
{
	cat("  Histogram of P-value distribution...\n")
	pv.col <- names(d3)[grep("^p\\.{0,1}val[e-u]{0,2}$", tolower(names(d3)))]
	hist(d3[[pv.col]],breaks=20, xlab="P Value", ylab="Frequency", main="P-value distribution")
}

